# Render.com deployment configuration
# This file should be named render.yaml and placed in the root of your repository

services:
  - type: web
    name: ttrpg-webhook-server
    env: python
    buildCommand: |
      cd server_host
      pip install -r requirements.txt
    startCommand: |
      cd server_host
      python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true
