"""PostgreSQL baseline for the current 24-table application schema.

Revision ID: 0001_postgresql_baseline
Revises:
Create Date: 2026-07-17 14:37:18.276166
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_postgresql_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('password_set_at', sa.DateTime(), nullable=True),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_verified'), 'users', ['is_verified'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('r2_asset_id', sa.String(length=100), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('xxhash', sa.String(length=32), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('r2_key', sa.String(length=500), nullable=False),
    sa.Column('r2_bucket', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_assets_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_asset_name'), 'assets', ['asset_name'], unique=False)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_r2_asset_id'), 'assets', ['r2_asset_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('session_code', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.Column('source_service', sa.String(length=100), nullable=False),
    sa.Column('service_version', sa.String(length=100), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_id'), 'audit_logs', ['event_id'], unique=True)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_outcome'), 'audit_logs', ['outcome'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_session_code'), 'audit_logs', ['session_code'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_trace_id'), 'audit_logs', ['trace_id'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_verification_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verification_tokens'))
    )
    op.create_index(op.f('ix_email_verification_tokens_id'), 'email_verification_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('session_code', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('game_data', sa.Text(), nullable=True),
    sa.Column('ban_list', sa.Text(), nullable=True),
    sa.Column('session_rules_json', sa.Text(), nullable=True),
    sa.Column('game_mode', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_game_sessions_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_sessions'))
    )
    op.create_index(op.f('ix_game_sessions_id'), 'game_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_game_sessions_is_demo'), 'game_sessions', ['is_demo'], unique=False)
    op.create_index(op.f('ix_game_sessions_session_code'), 'game_sessions', ['session_code'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens'))
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('pending_email_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('new_email', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pending_email_changes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_email_changes'))
    )
    op.create_index(op.f('ix_pending_email_changes_id'), 'pending_email_changes', ['id'], unique=False)
    op.create_index(op.f('ix_pending_email_changes_token_hash'), 'pending_email_changes', ['token_hash'], unique=True)
    op.create_index(op.f('ix_pending_email_changes_user_id'), 'pending_email_changes', ['user_id'], unique=False)
    op.create_table('asset_upload_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('r2_key', sa.String(length=500), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('session_code', sa.String(length=20), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('xxhash', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name=op.f('fk_asset_upload_intents_session_id_game_sessions')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_asset_upload_intents_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_upload_intents'))
    )
    op.create_index(op.f('ix_asset_upload_intents_asset_id'), 'asset_upload_intents', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_upload_intents_expires_at'), 'asset_upload_intents', ['expires_at'], unique=False)
    op.create_index(op.f('ix_asset_upload_intents_id'), 'asset_upload_intents', ['id'], unique=False)
    op.create_index(op.f('ix_asset_upload_intents_session_code'), 'asset_upload_intents', ['session_code'], unique=False)
    op.create_index(op.f('ix_asset_upload_intents_session_id'), 'asset_upload_intents', ['session_id'], unique=False)
    op.create_index(op.f('ix_asset_upload_intents_status'), 'asset_upload_intents', ['status'], unique=False)
    op.create_index(op.f('ix_asset_upload_intents_uploaded_by'), 'asset_upload_intents', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_asset_upload_intents_xxhash'), 'asset_upload_intents', ['xxhash'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('client_operation_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('message_json', sa.Text(), nullable=False),
    sa.Column('attachments_json', sa.Text(), nullable=True),
    sa.Column('client_timestamp', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_chat_messages_recipient_user_id_users')),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name=op.f('fk_chat_messages_session_id_game_sessions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_messages_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages')),
    sa.UniqueConstraint('session_id', 'user_id', 'client_operation_id', name='uq_chat_sender_operation')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_message_id'), 'chat_messages', ['message_id'], unique=True)
    op.create_index(op.f('ix_chat_messages_recipient_user_id'), 'chat_messages', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_table_id'), 'chat_messages', ['table_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('choice_encounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('session_code', sa.String(length=20), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('state_json', sa.Text(), nullable=False),
    sa.Column('participants_json', sa.Text(), nullable=False),
    sa.Column('choices_json', sa.Text(), nullable=False),
    sa.Column('dm_notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_choice_encounters_created_by_users')),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name=op.f('fk_choice_encounters_session_id_game_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_choice_encounters'))
    )
    op.create_index(op.f('ix_choice_encounters_encounter_id'), 'choice_encounters', ['encounter_id'], unique=True)
    op.create_index(op.f('ix_choice_encounters_id'), 'choice_encounters', ['id'], unique=False)
    op.create_index(op.f('ix_choice_encounters_session_code'), 'choice_encounters', ['session_code'], unique=False)
    op.create_index(op.f('ix_choice_encounters_session_id'), 'choice_encounters', ['session_id'], unique=False)
    op.create_table('combat_encounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('current_turn_index', sa.Integer(), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('combatants_json', sa.Text(), nullable=True),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.Column('action_log_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name=op.f('fk_combat_encounters_session_id_game_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_combat_encounters'))
    )
    op.create_index(op.f('ix_combat_encounters_encounter_id'), 'combat_encounters', ['encounter_id'], unique=True)
    op.create_index(op.f('ix_combat_encounters_id'), 'combat_encounters', ['id'], unique=False)
    op.create_table('game_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('active_table_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name=op.f('fk_game_players_session_id_game_sessions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_game_players_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_players')),
    sa.UniqueConstraint('session_id', 'user_id', name='uq_gameplayer_session_user')
    )
    op.create_index(op.f('ix_game_players_id'), 'game_players', ['id'], unique=False)
    op.create_table('session_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_session_assets_added_by_users')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_session_assets_asset_id_assets')),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name=op.f('fk_session_assets_session_id_game_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_assets')),
    sa.UniqueConstraint('session_id', 'asset_id', name='uq_session_asset')
    )
    op.create_index(op.f('ix_session_assets_asset_id'), 'session_assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_session_assets_id'), 'session_assets', ['id'], unique=False)
    op.create_index(op.f('ix_session_assets_session_id'), 'session_assets', ['session_id'], unique=False)
    op.create_table('session_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=255), nullable=False),
    sa.Column('character_data', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_modified_by', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['archived_by'], ['users.id'], name=op.f('fk_session_characters_archived_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], name=op.f('fk_session_characters_last_modified_by_users')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_session_characters_owner_user_id_users')),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name=op.f('fk_session_characters_session_id_game_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_characters'))
    )
    op.create_index(op.f('ix_session_characters_archived_at'), 'session_characters', ['archived_at'], unique=False)
    op.create_index(op.f('ix_session_characters_character_id'), 'session_characters', ['character_id'], unique=True)
    op.create_index(op.f('ix_session_characters_id'), 'session_characters', ['id'], unique=False)
    op.create_table('session_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('pre_assigned_role', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('uses_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_session_invitations_created_by_users')),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name=op.f('fk_session_invitations_session_id_game_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_invitations'))
    )
    op.create_index(op.f('ix_session_invitations_id'), 'session_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_session_invitations_invite_code'), 'session_invitations', ['invite_code'], unique=True)
    op.create_table('virtual_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('scale_x', sa.Float(), nullable=False),
    sa.Column('scale_y', sa.Float(), nullable=False),
    sa.Column('layer_visibility', sa.Text(), nullable=True),
    sa.Column('layer_settings', sa.Text(), nullable=True),
    sa.Column('dynamic_lighting_enabled', sa.Boolean(), nullable=False),
    sa.Column('fog_exploration_mode', sa.String(length=20), nullable=True),
    sa.Column('ambient_light_level', sa.Float(), nullable=False),
    sa.Column('grid_cell_px', sa.Float(), nullable=False),
    sa.Column('cell_distance', sa.Float(), nullable=False),
    sa.Column('distance_unit', sa.String(length=10), nullable=True),
    sa.Column('grid_enabled', sa.Boolean(), nullable=False),
    sa.Column('snap_to_grid', sa.Boolean(), nullable=False),
    sa.Column('grid_color_hex', sa.String(length=9), nullable=True),
    sa.Column('background_color_hex', sa.String(length=9), nullable=True),
    sa.Column('difficult_terrain_json', sa.Text(), nullable=True),
    sa.Column('cover_zones_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name=op.f('fk_virtual_tables_session_id_game_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_virtual_tables'))
    )
    op.create_index(op.f('ix_virtual_tables_id'), 'virtual_tables', ['id'], unique=False)
    op.create_index(op.f('ix_virtual_tables_table_id'), 'virtual_tables', ['table_id'], unique=True)
    op.create_table('character_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('draft_data', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('converted_character_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['converted_character_id'], ['session_characters.character_id'], name=op.f('fk_character_drafts_converted_character_id_session_characters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], name=op.f('fk_character_drafts_last_modified_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_character_drafts_owner_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name=op.f('fk_character_drafts_session_id_game_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_drafts'))
    )
    op.create_index(op.f('ix_character_drafts_draft_id'), 'character_drafts', ['draft_id'], unique=True)
    op.create_index(op.f('ix_character_drafts_id'), 'character_drafts', ['id'], unique=False)
    op.create_index(op.f('ix_character_drafts_owner_user_id'), 'character_drafts', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_character_drafts_session_id'), 'character_drafts', ['session_id'], unique=False)
    op.create_index(op.f('ix_character_drafts_status'), 'character_drafts', ['status'], unique=False)
    op.create_index(op.f('ix_character_drafts_updated_at'), 'character_drafts', ['updated_at'], unique=False)
    op.create_table('character_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['session_characters.character_id'], name=op.f('fk_character_logs_character_id_session_characters')),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name=op.f('fk_character_logs_session_id_game_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_logs'))
    )
    op.create_index(op.f('ix_character_logs_character_id'), 'character_logs', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_logs_created_at'), 'character_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_character_logs_id'), 'character_logs', ['id'], unique=False)
    op.create_table('character_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_control', sa.Boolean(), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['session_characters.character_id'], name=op.f('fk_character_permissions_character_id_session_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_character_permissions_granted_by_users')),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name=op.f('fk_character_permissions_session_id_game_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_character_permissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_permissions')),
    sa.UniqueConstraint('character_id', 'user_id', name='uq_character_permission_user')
    )
    op.create_index(op.f('ix_character_permissions_character_id'), 'character_permissions', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_permissions_session_id'), 'character_permissions', ['session_id'], unique=False)
    op.create_index(op.f('ix_character_permissions_user_id'), 'character_permissions', ['user_id'], unique=False)
    op.create_table('choice_encounter_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['choice_encounters.encounter_id'], name=op.f('fk_choice_encounter_events_encounter_id_choice_encounters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_choice_encounter_events')),
    sa.UniqueConstraint('encounter_id', 'sequence', name='uq_choice_encounter_event_sequence')
    )
    op.create_index(op.f('ix_choice_encounter_events_created_at'), 'choice_encounter_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_choice_encounter_events_encounter_id'), 'choice_encounter_events', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_choice_encounter_events_id'), 'choice_encounter_events', ['id'], unique=False)
    op.create_table('combat_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.String(length=36), nullable=False),
    sa.Column('requester_key', sa.String(length=128), nullable=False),
    sa.Column('sequence_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('command_type', sa.String(length=50), nullable=False),
    sa.Column('command_payload_json', sa.Text(), nullable=False),
    sa.Column('result_payload_json', sa.Text(), nullable=False),
    sa.Column('state_before_json', sa.Text(), nullable=False),
    sa.Column('state_after_hash', sa.String(length=64), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_combat_actions_created_by_users')),
    sa.ForeignKeyConstraint(['encounter_id'], ['combat_encounters.encounter_id'], name=op.f('fk_combat_actions_encounter_id_combat_encounters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_combat_actions')),
    sa.UniqueConstraint('encounter_id', 'requester_key', 'sequence_id', name='uq_combat_action_request')
    )
    op.create_index(op.f('ix_combat_actions_encounter_id'), 'combat_actions', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_combat_actions_id'), 'combat_actions', ['id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('sprite_id', sa.String(length=36), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('layer', sa.String(length=50), nullable=False),
    sa.Column('texture_path', sa.String(length=500), nullable=True),
    sa.Column('asset_id', sa.String(length=100), nullable=True),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=True),
    sa.Column('controlled_by', sa.Text(), nullable=True),
    sa.Column('scale_x', sa.Float(), nullable=False),
    sa.Column('scale_y', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Float(), nullable=False),
    sa.Column('obstacle_type', sa.String(length=20), nullable=True),
    sa.Column('obstacle_data', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('max_hp', sa.Integer(), nullable=True),
    sa.Column('ac', sa.Integer(), nullable=True),
    sa.Column('aura_radius', sa.Float(), nullable=True),
    sa.Column('aura_color', sa.String(length=7), nullable=True),
    sa.Column('vision_radius', sa.Float(), nullable=True),
    sa.Column('has_darkvision', sa.Boolean(), nullable=False),
    sa.Column('darkvision_radius', sa.Float(), nullable=True),
    sa.Column('aura_radius_units', sa.Float(), nullable=True),
    sa.Column('vision_radius_units', sa.Float(), nullable=True),
    sa.Column('darkvision_radius_units', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['session_characters.character_id'], name=op.f('fk_entities_character_id_session_characters')),
    sa.ForeignKeyConstraint(['table_id'], ['virtual_tables.id'], name=op.f('fk_entities_table_id_virtual_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities'))
    )
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.create_index(op.f('ix_entities_sprite_id'), 'entities', ['sprite_id'], unique=True)
    op.create_table('paint_strokes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stroke_id', sa.String(length=36), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('stroke_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_paint_strokes_created_by_users')),
    sa.ForeignKeyConstraint(['table_id'], ['virtual_tables.table_id'], name=op.f('fk_paint_strokes_table_id_virtual_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paint_strokes'))
    )
    op.create_index(op.f('ix_paint_strokes_id'), 'paint_strokes', ['id'], unique=False)
    op.create_index(op.f('ix_paint_strokes_stroke_id'), 'paint_strokes', ['stroke_id'], unique=True)
    op.create_index(op.f('ix_paint_strokes_table_id'), 'paint_strokes', ['table_id'], unique=False)
    op.create_table('walls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wall_id', sa.String(length=36), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=False),
    sa.Column('x1', sa.Float(), nullable=False),
    sa.Column('y1', sa.Float(), nullable=False),
    sa.Column('x2', sa.Float(), nullable=False),
    sa.Column('y2', sa.Float(), nullable=False),
    sa.Column('wall_type', sa.String(length=20), nullable=False),
    sa.Column('blocks_movement', sa.Boolean(), nullable=False),
    sa.Column('blocks_light', sa.Boolean(), nullable=False),
    sa.Column('blocks_sight', sa.Boolean(), nullable=False),
    sa.Column('blocks_sound', sa.Boolean(), nullable=False),
    sa.Column('is_door', sa.Boolean(), nullable=False),
    sa.Column('door_state', sa.String(length=10), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_walls_created_by_users')),
    sa.ForeignKeyConstraint(['table_id'], ['virtual_tables.table_id'], name=op.f('fk_walls_table_id_virtual_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_walls'))
    )
    op.create_index(op.f('ix_walls_id'), 'walls', ['id'], unique=False)
    op.create_index(op.f('ix_walls_table_id'), 'walls', ['table_id'], unique=False)
    op.create_index(op.f('ix_walls_wall_id'), 'walls', ['wall_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_walls_wall_id'), table_name='walls')
    op.drop_index(op.f('ix_walls_table_id'), table_name='walls')
    op.drop_index(op.f('ix_walls_id'), table_name='walls')
    op.drop_table('walls')
    op.drop_index(op.f('ix_paint_strokes_table_id'), table_name='paint_strokes')
    op.drop_index(op.f('ix_paint_strokes_stroke_id'), table_name='paint_strokes')
    op.drop_index(op.f('ix_paint_strokes_id'), table_name='paint_strokes')
    op.drop_table('paint_strokes')
    op.drop_index(op.f('ix_entities_sprite_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_combat_actions_id'), table_name='combat_actions')
    op.drop_index(op.f('ix_combat_actions_encounter_id'), table_name='combat_actions')
    op.drop_table('combat_actions')
    op.drop_index(op.f('ix_choice_encounter_events_id'), table_name='choice_encounter_events')
    op.drop_index(op.f('ix_choice_encounter_events_encounter_id'), table_name='choice_encounter_events')
    op.drop_index(op.f('ix_choice_encounter_events_created_at'), table_name='choice_encounter_events')
    op.drop_table('choice_encounter_events')
    op.drop_index(op.f('ix_character_permissions_user_id'), table_name='character_permissions')
    op.drop_index(op.f('ix_character_permissions_session_id'), table_name='character_permissions')
    op.drop_index(op.f('ix_character_permissions_character_id'), table_name='character_permissions')
    op.drop_table('character_permissions')
    op.drop_index(op.f('ix_character_logs_id'), table_name='character_logs')
    op.drop_index(op.f('ix_character_logs_created_at'), table_name='character_logs')
    op.drop_index(op.f('ix_character_logs_character_id'), table_name='character_logs')
    op.drop_table('character_logs')
    op.drop_index(op.f('ix_character_drafts_updated_at'), table_name='character_drafts')
    op.drop_index(op.f('ix_character_drafts_status'), table_name='character_drafts')
    op.drop_index(op.f('ix_character_drafts_session_id'), table_name='character_drafts')
    op.drop_index(op.f('ix_character_drafts_owner_user_id'), table_name='character_drafts')
    op.drop_index(op.f('ix_character_drafts_id'), table_name='character_drafts')
    op.drop_index(op.f('ix_character_drafts_draft_id'), table_name='character_drafts')
    op.drop_table('character_drafts')
    op.drop_index(op.f('ix_virtual_tables_table_id'), table_name='virtual_tables')
    op.drop_index(op.f('ix_virtual_tables_id'), table_name='virtual_tables')
    op.drop_table('virtual_tables')
    op.drop_index(op.f('ix_session_invitations_invite_code'), table_name='session_invitations')
    op.drop_index(op.f('ix_session_invitations_id'), table_name='session_invitations')
    op.drop_table('session_invitations')
    op.drop_index(op.f('ix_session_characters_id'), table_name='session_characters')
    op.drop_index(op.f('ix_session_characters_character_id'), table_name='session_characters')
    op.drop_index(op.f('ix_session_characters_archived_at'), table_name='session_characters')
    op.drop_table('session_characters')
    op.drop_index(op.f('ix_session_assets_session_id'), table_name='session_assets')
    op.drop_index(op.f('ix_session_assets_id'), table_name='session_assets')
    op.drop_index(op.f('ix_session_assets_asset_id'), table_name='session_assets')
    op.drop_table('session_assets')
    op.drop_index(op.f('ix_game_players_id'), table_name='game_players')
    op.drop_table('game_players')
    op.drop_index(op.f('ix_combat_encounters_id'), table_name='combat_encounters')
    op.drop_index(op.f('ix_combat_encounters_encounter_id'), table_name='combat_encounters')
    op.drop_table('combat_encounters')
    op.drop_index(op.f('ix_choice_encounters_session_id'), table_name='choice_encounters')
    op.drop_index(op.f('ix_choice_encounters_session_code'), table_name='choice_encounters')
    op.drop_index(op.f('ix_choice_encounters_id'), table_name='choice_encounters')
    op.drop_index(op.f('ix_choice_encounters_encounter_id'), table_name='choice_encounters')
    op.drop_table('choice_encounters')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_table_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_recipient_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_message_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_asset_upload_intents_xxhash'), table_name='asset_upload_intents')
    op.drop_index(op.f('ix_asset_upload_intents_uploaded_by'), table_name='asset_upload_intents')
    op.drop_index(op.f('ix_asset_upload_intents_status'), table_name='asset_upload_intents')
    op.drop_index(op.f('ix_asset_upload_intents_session_id'), table_name='asset_upload_intents')
    op.drop_index(op.f('ix_asset_upload_intents_session_code'), table_name='asset_upload_intents')
    op.drop_index(op.f('ix_asset_upload_intents_id'), table_name='asset_upload_intents')
    op.drop_index(op.f('ix_asset_upload_intents_expires_at'), table_name='asset_upload_intents')
    op.drop_index(op.f('ix_asset_upload_intents_asset_id'), table_name='asset_upload_intents')
    op.drop_table('asset_upload_intents')
    op.drop_index(op.f('ix_pending_email_changes_user_id'), table_name='pending_email_changes')
    op.drop_index(op.f('ix_pending_email_changes_token_hash'), table_name='pending_email_changes')
    op.drop_index(op.f('ix_pending_email_changes_id'), table_name='pending_email_changes')
    op.drop_table('pending_email_changes')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_game_sessions_session_code'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_is_demo'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_id'), table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_id'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_audit_logs_trace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_session_code'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_outcome'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assets_r2_asset_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_name'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_verified'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
