[OK]#[OK]![OK]/[OK]u[OK]s[OK]r[OK]/[OK]b[OK]i[OK]n[OK]/[OK]e[OK]n[OK]v[OK] [OK]p[OK]y[OK]t[OK]h[OK]o[OK]n[OK]3[OK]
[OK]"[OK]"[OK]"[OK]
[OK]C[OK]o[OK]m[OK]p[OK]r[OK]e[OK]h[OK]e[OK]n[OK]s[OK]i[OK]v[OK]e[OK] [OK]t[OK]e[OK]s[OK]t[OK] [OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK] [OK]f[OK]o[OK]r[OK] [OK]t[OK]h[OK]e[OK] [OK]T[OK]T[OK]R[OK]P[OK]G[OK] [OK]W[OK]e[OK]b[OK]h[OK]o[OK]o[OK]k[OK] [OK]S[OK]e[OK]r[OK]v[OK]e[OK]r[OK]
[OK]T[OK]e[OK]s[OK]t[OK]s[OK] [OK]a[OK]l[OK]l[OK] [OK]m[OK]a[OK]j[OK]o[OK]r[OK] [OK]f[OK]u[OK]n[OK]c[OK]t[OK]i[OK]o[OK]n[OK]a[OK]l[OK]i[OK]t[OK]y[OK] [OK]o[OK]f[OK] [OK]t[OK]h[OK]e[OK] [OK]w[OK]e[OK]b[OK]h[OK]o[OK]o[OK]k[OK]-[OK]b[OK]a[OK]s[OK]e[OK]d[OK] [OK]s[OK]e[OK]r[OK]v[OK]e[OK]r[OK]
[OK]"[OK]"[OK]"[OK]
[OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK]i[OK]o[OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]a[OK]i[OK]o[OK]h[OK]t[OK]t[OK]p[OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]j[OK]s[OK]o[OK]n[OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]t[OK]i[OK]m[OK]e[OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]l[OK]o[OK]g[OK]g[OK]i[OK]n[OK]g[OK]
[OK]
[OK]#[OK] [OK]C[OK]o[OK]n[OK]f[OK]i[OK]g[OK]u[OK]r[OK]e[OK] [OK]l[OK]o[OK]g[OK]g[OK]i[OK]n[OK]g[OK]
[OK]l[OK]o[OK]g[OK]g[OK]i[OK]n[OK]g[OK].[OK]b[OK]a[OK]s[OK]i[OK]c[OK]C[OK]o[OK]n[OK]f[OK]i[OK]g[OK]([OK]l[OK]e[OK]v[OK]e[OK]l[OK]=[OK]l[OK]o[OK]g[OK]g[OK]i[OK]n[OK]g[OK].[OK]I[OK]N[OK]F[OK]O[OK])[OK]
[OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK] [OK]=[OK] [OK]l[OK]o[OK]g[OK]g[OK]i[OK]n[OK]g[OK].[OK]g[OK]e[OK]t[OK]L[OK]o[OK]g[OK]g[OK]e[OK]r[OK]([OK]_[OK]_[OK]n[OK]a[OK]m[OK]e[OK]_[OK]_[OK])[OK]
[OK]
[OK]c[OK]l[OK]a[OK]s[OK]s[OK] [OK]S[OK]e[OK]r[OK]v[OK]e[OK]r[OK]T[OK]e[OK]s[OK]t[OK]e[OK]r[OK]:[OK]
[OK] [OK] [OK] [OK] [OK]d[OK]e[OK]f[OK] [OK]_[OK]_[OK]i[OK]n[OK]i[OK]t[OK]_[OK]_[OK]([OK]s[OK]e[OK]l[OK]f[OK],[OK] [OK]b[OK]a[OK]s[OK]e[OK]_[OK]u[OK]r[OK]l[OK]:[OK] [OK]s[OK]t[OK]r[OK] [OK]=[OK] [OK]"[OK]h[OK]t[OK]t[OK]p[OK]:[OK]/[OK]/[OK]1[OK]2[OK]7[OK].[OK]0[OK].[OK]0[OK].[OK]1[OK]:[OK]8[OK]0[OK]0[OK]0[OK]"[OK])[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]s[OK]e[OK]l[OK]f[OK].[OK]b[OK]a[OK]s[OK]e[OK]_[OK]u[OK]r[OK]l[OK] [OK]=[OK] [OK]b[OK]a[OK]s[OK]e[OK]_[OK]u[OK]r[OK]l[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]s[OK]e[OK]l[OK]f[OK].[OK]s[OK]e[OK]s[OK]s[OK]i[OK]o[OK]n[OK] [OK]=[OK] [OK]N[OK]o[OK]n[OK]e[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]d[OK]e[OK]f[OK] [OK]_[OK]_[OK]a[OK]e[OK]n[OK]t[OK]e[OK]r[OK]_[OK]_[OK]([OK]s[OK]e[OK]l[OK]f[OK])[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]s[OK]e[OK]l[OK]f[OK].[OK]s[OK]e[OK]s[OK]s[OK]i[OK]o[OK]n[OK] [OK]=[OK] [OK]a[OK]i[OK]o[OK]h[OK]t[OK]t[OK]p[OK].[OK]C[OK]l[OK]i[OK]e[OK]n[OK]t[OK]S[OK]e[OK]s[OK]s[OK]i[OK]o[OK]n[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]s[OK]e[OK]l[OK]f[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]d[OK]e[OK]f[OK] [OK]_[OK]_[OK]a[OK]e[OK]x[OK]i[OK]t[OK]_[OK]_[OK]([OK]s[OK]e[OK]l[OK]f[OK],[OK] [OK]e[OK]x[OK]c[OK]_[OK]t[OK]y[OK]p[OK]e[OK],[OK] [OK]e[OK]x[OK]c[OK]_[OK]v[OK]a[OK]l[OK],[OK] [OK]e[OK]x[OK]c[OK]_[OK]t[OK]b[OK])[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]s[OK]e[OK]l[OK]f[OK].[OK]s[OK]e[OK]s[OK]s[OK]i[OK]o[OK]n[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]s[OK]e[OK]l[OK]f[OK].[OK]s[OK]e[OK]s[OK]s[OK]i[OK]o[OK]n[OK].[OK]c[OK]l[OK]o[OK]s[OK]e[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]d[OK]e[OK]f[OK] [OK]t[OK]e[OK]s[OK]t[OK]_[OK]s[OK]e[OK]r[OK]v[OK]e[OK]r[OK]_[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK]([OK]s[OK]e[OK]l[OK]f[OK])[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]T[OK]e[OK]s[OK]t[OK] [OK]s[OK]e[OK]r[OK]v[OK]e[OK]r[OK] [OK]r[OK]o[OK]o[OK]t[OK] [OK]a[OK]n[OK]d[OK] [OK]h[OK]e[OK]a[OK]l[OK]t[OK]h[OK] [OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK]s[OK]"[OK]"[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]T[OK]e[OK]s[OK]t[OK]i[OK]n[OK]g[OK] [OK]s[OK]e[OK]r[OK]v[OK]e[OK]r[OK] [OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK].[OK].[OK].[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]T[OK]e[OK]s[OK]t[OK] [OK]r[OK]o[OK]o[OK]t[OK] [OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]s[OK]e[OK]l[OK]f[OK].[OK]s[OK]e[OK]s[OK]s[OK]i[OK]o[OK]n[OK].[OK]g[OK]e[OK]t[OK]([OK]f[OK]"[OK]{[OK]s[OK]e[OK]l[OK]f[OK].[OK]b[OK]a[OK]s[OK]e[OK]_[OK]u[OK]r[OK]l[OK]}[OK]/[OK]"[OK])[OK] [OK]a[OK]s[OK] [OK]r[OK]e[OK]s[OK]p[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK] [OK]=[OK]=[OK] [OK]2[OK]0[OK]0[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]a[OK]t[OK]a[OK] [OK]=[OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]j[OK]s[OK]o[OK]n[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]"[OK]r[OK]u[OK]n[OK]n[OK]i[OK]n[OK]g[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]s[OK]e[OK]r[OK]v[OK]e[OK]r[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]"[OK]T[OK]T[OK]R[OK]P[OK]G[OK] [OK]W[OK]e[OK]b[OK]h[OK]o[OK]o[OK]k[OK] [OK]S[OK]e[OK]r[OK]v[OK]e[OK]r[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]✅[OK] [OK]R[OK]o[OK]o[OK]t[OK] [OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK] [OK]w[OK]o[OK]r[OK]k[OK]i[OK]n[OK]g[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]T[OK]e[OK]s[OK]t[OK] [OK]h[OK]e[OK]a[OK]l[OK]t[OK]h[OK] [OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]s[OK]e[OK]l[OK]f[OK].[OK]s[OK]e[OK]s[OK]s[OK]i[OK]o[OK]n[OK].[OK]g[OK]e[OK]t[OK]([OK]f[OK]"[OK]{[OK]s[OK]e[OK]l[OK]f[OK].[OK]b[OK]a[OK]s[OK]e[OK]_[OK]u[OK]r[OK]l[OK]}[OK]/[OK]h[OK]e[OK]a[OK]l[OK]t[OK]h[OK]"[OK])[OK] [OK]a[OK]s[OK] [OK]r[OK]e[OK]s[OK]p[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK] [OK]=[OK]=[OK] [OK]2[OK]0[OK]0[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]a[OK]t[OK]a[OK] [OK]=[OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]j[OK]s[OK]o[OK]n[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]"[OK]h[OK]e[OK]a[OK]l[OK]t[OK]h[OK]y[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]s[OK]e[OK]r[OK]v[OK]e[OK]r[OK]_[OK]r[OK]u[OK]n[OK]n[OK]i[OK]n[OK]g[OK]"[OK]][OK] [OK]i[OK]s[OK] [OK]T[OK]r[OK]u[OK]e[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]✅[OK] [OK]H[OK]e[OK]a[OK]l[OK]t[OK]h[OK] [OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK] [OK]w[OK]o[OK]r[OK]k[OK]i[OK]n[OK]g[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]d[OK]e[OK]f[OK] [OK]t[OK]e[OK]s[OK]t[OK]_[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]r[OK]e[OK]g[OK]i[OK]s[OK]t[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK]([OK]s[OK]e[OK]l[OK]f[OK])[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]T[OK]e[OK]s[OK]t[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK] [OK]r[OK]e[OK]g[OK]i[OK]s[OK]t[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK] [OK]a[OK]n[OK]d[OK] [OK]l[OK]i[OK]s[OK]t[OK]i[OK]n[OK]g[OK]"[OK]"[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]T[OK]e[OK]s[OK]t[OK]i[OK]n[OK]g[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK] [OK]r[OK]e[OK]g[OK]i[OK]s[OK]t[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK].[OK].[OK].[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]R[OK]e[OK]g[OK]i[OK]s[OK]t[OK]e[OK]r[OK] [OK]a[OK] [OK]t[OK]e[OK]s[OK]t[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]d[OK]a[OK]t[OK]a[OK] [OK]=[OK] [OK]{[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK]"[OK]:[OK] [OK]"[OK]t[OK]e[OK]s[OK]t[OK]-[OK]c[OK]o[OK]m[OK]p[OK]r[OK]e[OK]h[OK]e[OK]n[OK]s[OK]i[OK]v[OK]e[OK]-[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]"[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]w[OK]e[OK]b[OK]h[OK]o[OK]o[OK]k[OK]_[OK]u[OK]r[OK]l[OK]"[OK]:[OK] [OK]"[OK]h[OK]t[OK]t[OK]p[OK]:[OK]/[OK]/[OK]l[OK]o[OK]c[OK]a[OK]l[OK]h[OK]o[OK]s[OK]t[OK]:[OK]9[OK]9[OK]9[OK]9[OK]/[OK]w[OK]e[OK]b[OK]h[OK]o[OK]o[OK]k[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]}[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]s[OK]e[OK]l[OK]f[OK].[OK]s[OK]e[OK]s[OK]s[OK]i[OK]o[OK]n[OK].[OK]p[OK]o[OK]s[OK]t[OK]([OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]"[OK]{[OK]s[OK]e[OK]l[OK]f[OK].[OK]b[OK]a[OK]s[OK]e[OK]_[OK]u[OK]r[OK]l[OK]}[OK]/[OK]a[OK]p[OK]i[OK]/[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]/[OK]r[OK]e[OK]g[OK]i[OK]s[OK]t[OK]e[OK]r[OK]"[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]j[OK]s[OK]o[OK]n[OK]=[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]d[OK]a[OK]t[OK]a[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK] [OK]a[OK]s[OK] [OK]r[OK]e[OK]s[OK]p[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK] [OK]=[OK]=[OK] [OK]2[OK]0[OK]0[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]a[OK]t[OK]a[OK] [OK]=[OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]j[OK]s[OK]o[OK]n[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]"[OK]r[OK]e[OK]g[OK]i[OK]s[OK]t[OK]e[OK]r[OK]e[OK]d[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]"[OK]t[OK]e[OK]s[OK]t[OK]-[OK]c[OK]o[OK]m[OK]p[OK]r[OK]e[OK]h[OK]e[OK]n[OK]s[OK]i[OK]v[OK]e[OK]-[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]✅[OK] [OK]C[OK]l[OK]i[OK]e[OK]n[OK]t[OK] [OK]r[OK]e[OK]g[OK]i[OK]s[OK]t[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK] [OK]w[OK]o[OK]r[OK]k[OK]i[OK]n[OK]g[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]C[OK]h[OK]e[OK]c[OK]k[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK] [OK]l[OK]i[OK]s[OK]t[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]s[OK]e[OK]l[OK]f[OK].[OK]s[OK]e[OK]s[OK]s[OK]i[OK]o[OK]n[OK].[OK]g[OK]e[OK]t[OK]([OK]f[OK]"[OK]{[OK]s[OK]e[OK]l[OK]f[OK].[OK]b[OK]a[OK]s[OK]e[OK]_[OK]u[OK]r[OK]l[OK]}[OK]/[OK]a[OK]p[OK]i[OK]/[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]s[OK]"[OK])[OK] [OK]a[OK]s[OK] [OK]r[OK]e[OK]s[OK]p[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK] [OK]=[OK]=[OK] [OK]2[OK]0[OK]0[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]a[OK]t[OK]a[OK] [OK]=[OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]j[OK]s[OK]o[OK]n[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]"[OK]s[OK]u[OK]c[OK]c[OK]e[OK]s[OK]s[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]F[OK]i[OK]n[OK]d[OK] [OK]o[OK]u[OK]r[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]f[OK]o[OK]u[OK]n[OK]d[OK] [OK]=[OK] [OK]F[OK]a[OK]l[OK]s[OK]e[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK] [OK]i[OK]n[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]s[OK]"[OK]][OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK][[OK]"[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]"[OK]t[OK]e[OK]s[OK]t[OK]-[OK]c[OK]o[OK]m[OK]p[OK]r[OK]e[OK]h[OK]e[OK]n[OK]s[OK]i[OK]v[OK]e[OK]-[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]"[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]f[OK]o[OK]u[OK]n[OK]d[OK] [OK]=[OK] [OK]T[OK]r[OK]u[OK]e[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]r[OK]e[OK]a[OK]k[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]f[OK]o[OK]u[OK]n[OK]d[OK],[OK] [OK]"[OK]R[OK]e[OK]g[OK]i[OK]s[OK]t[OK]e[OK]r[OK]e[OK]d[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK] [OK]n[OK]o[OK]t[OK] [OK]f[OK]o[OK]u[OK]n[OK]d[OK] [OK]i[OK]n[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK] [OK]l[OK]i[OK]s[OK]t[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]✅[OK] [OK]C[OK]l[OK]i[OK]e[OK]n[OK]t[OK] [OK]l[OK]i[OK]s[OK]t[OK]i[OK]n[OK]g[OK] [OK]w[OK]o[OK]r[OK]k[OK]i[OK]n[OK]g[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]"[OK]t[OK]e[OK]s[OK]t[OK]-[OK]c[OK]o[OK]m[OK]p[OK]r[OK]e[OK]h[OK]e[OK]n[OK]s[OK]i[OK]v[OK]e[OK]-[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]"[OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]d[OK]e[OK]f[OK] [OK]t[OK]e[OK]s[OK]t[OK]_[OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK]_[OK]h[OK]a[OK]n[OK]d[OK]l[OK]i[OK]n[OK]g[OK]([OK]s[OK]e[OK]l[OK]f[OK],[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK]:[OK] [OK]s[OK]t[OK]r[OK])[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]T[OK]e[OK]s[OK]t[OK] [OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK] [OK]s[OK]e[OK]n[OK]d[OK]i[OK]n[OK]g[OK] [OK]a[OK]n[OK]d[OK] [OK]h[OK]a[OK]n[OK]d[OK]l[OK]i[OK]n[OK]g[OK]"[OK]"[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]T[OK]e[OK]s[OK]t[OK]i[OK]n[OK]g[OK] [OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK] [OK]h[OK]a[OK]n[OK]d[OK]l[OK]i[OK]n[OK]g[OK].[OK].[OK].[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]T[OK]e[OK]s[OK]t[OK] [OK]P[OK]I[OK]N[OK]G[OK] [OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]i[OK]n[OK]g[OK]_[OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK] [OK]=[OK] [OK]{[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK]"[OK]:[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK]"[OK]:[OK] [OK]{[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]t[OK]y[OK]p[OK]e[OK]"[OK]:[OK] [OK]"[OK]p[OK]i[OK]n[OK]g[OK]"[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]a[OK]t[OK]a[OK]"[OK]:[OK] [OK]{[OK]"[OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK]"[OK]:[OK] [OK]"[OK]T[OK]e[OK]s[OK]t[OK] [OK]p[OK]i[OK]n[OK]g[OK] [OK]f[OK]r[OK]o[OK]m[OK] [OK]c[OK]o[OK]m[OK]p[OK]r[OK]e[OK]h[OK]e[OK]n[OK]s[OK]i[OK]v[OK]e[OK] [OK]t[OK]e[OK]s[OK]t[OK]"[OK]}[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]}[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]}[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]s[OK]e[OK]l[OK]f[OK].[OK]s[OK]e[OK]s[OK]s[OK]i[OK]o[OK]n[OK].[OK]p[OK]o[OK]s[OK]t[OK]([OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]"[OK]{[OK]s[OK]e[OK]l[OK]f[OK].[OK]b[OK]a[OK]s[OK]e[OK]_[OK]u[OK]r[OK]l[OK]}[OK]/[OK]a[OK]p[OK]i[OK]/[OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK]"[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]j[OK]s[OK]o[OK]n[OK]=[OK]p[OK]i[OK]n[OK]g[OK]_[OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK] [OK]a[OK]s[OK] [OK]r[OK]e[OK]s[OK]p[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK] [OK]=[OK]=[OK] [OK]2[OK]0[OK]0[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]a[OK]t[OK]a[OK] [OK]=[OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]j[OK]s[OK]o[OK]n[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]"[OK]r[OK]e[OK]c[OK]e[OK]i[OK]v[OK]e[OK]d[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]✅[OK] [OK]P[OK]I[OK]N[OK]G[OK] [OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK] [OK]h[OK]a[OK]n[OK]d[OK]l[OK]i[OK]n[OK]g[OK] [OK]w[OK]o[OK]r[OK]k[OK]i[OK]n[OK]g[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]T[OK]e[OK]s[OK]t[OK] [OK]T[OK]E[OK]S[OK]T[OK] [OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]e[OK]s[OK]t[OK]_[OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK] [OK]=[OK] [OK]{[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK]"[OK]:[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK]"[OK]:[OK] [OK]{[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]t[OK]y[OK]p[OK]e[OK]"[OK]:[OK] [OK]"[OK]t[OK]e[OK]s[OK]t[OK]"[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]a[OK]t[OK]a[OK]"[OK]:[OK] [OK]{[OK]"[OK]t[OK]e[OK]s[OK]t[OK]_[OK]d[OK]a[OK]t[OK]a[OK]"[OK]:[OK] [OK]"[OK]C[OK]o[OK]m[OK]p[OK]r[OK]e[OK]h[OK]e[OK]n[OK]s[OK]i[OK]v[OK]e[OK] [OK]t[OK]e[OK]s[OK]t[OK] [OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK]"[OK]}[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]}[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]}[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]s[OK]e[OK]l[OK]f[OK].[OK]s[OK]e[OK]s[OK]s[OK]i[OK]o[OK]n[OK].[OK]p[OK]o[OK]s[OK]t[OK]([OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]"[OK]{[OK]s[OK]e[OK]l[OK]f[OK].[OK]b[OK]a[OK]s[OK]e[OK]_[OK]u[OK]r[OK]l[OK]}[OK]/[OK]a[OK]p[OK]i[OK]/[OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK]"[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]j[OK]s[OK]o[OK]n[OK]=[OK]t[OK]e[OK]s[OK]t[OK]_[OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK] [OK]a[OK]s[OK] [OK]r[OK]e[OK]s[OK]p[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK] [OK]=[OK]=[OK] [OK]2[OK]0[OK]0[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]a[OK]t[OK]a[OK] [OK]=[OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]j[OK]s[OK]o[OK]n[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]"[OK]r[OK]e[OK]c[OK]e[OK]i[OK]v[OK]e[OK]d[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]✅[OK] [OK]T[OK]E[OK]S[OK]T[OK] [OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK] [OK]h[OK]a[OK]n[OK]d[OK]l[OK]i[OK]n[OK]g[OK] [OK]w[OK]o[OK]r[OK]k[OK]i[OK]n[OK]g[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]T[OK]e[OK]s[OK]t[OK] [OK]T[OK]A[OK]B[OK]L[OK]E[OK]_[OK]R[OK]E[OK]Q[OK]U[OK]E[OK]S[OK]T[OK] [OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK]_[OK]r[OK]e[OK]q[OK]u[OK]e[OK]s[OK]t[OK] [OK]=[OK] [OK]{[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK]"[OK]:[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK]"[OK]:[OK] [OK]{[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]t[OK]y[OK]p[OK]e[OK]"[OK]:[OK] [OK]"[OK]t[OK]a[OK]b[OK]l[OK]e[OK]_[OK]r[OK]e[OK]q[OK]u[OK]e[OK]s[OK]t[OK]"[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]d[OK]a[OK]t[OK]a[OK]"[OK]:[OK] [OK]{[OK]"[OK]n[OK]a[OK]m[OK]e[OK]"[OK]:[OK] [OK]"[OK]d[OK]e[OK]f[OK]a[OK]u[OK]l[OK]t[OK]"[OK]}[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]}[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]}[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]s[OK]e[OK]l[OK]f[OK].[OK]s[OK]e[OK]s[OK]s[OK]i[OK]o[OK]n[OK].[OK]p[OK]o[OK]s[OK]t[OK]([OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]"[OK]{[OK]s[OK]e[OK]l[OK]f[OK].[OK]b[OK]a[OK]s[OK]e[OK]_[OK]u[OK]r[OK]l[OK]}[OK]/[OK]a[OK]p[OK]i[OK]/[OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK]"[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]j[OK]s[OK]o[OK]n[OK]=[OK]t[OK]a[OK]b[OK]l[OK]e[OK]_[OK]r[OK]e[OK]q[OK]u[OK]e[OK]s[OK]t[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK] [OK]a[OK]s[OK] [OK]r[OK]e[OK]s[OK]p[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK] [OK]=[OK]=[OK] [OK]2[OK]0[OK]0[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]a[OK]t[OK]a[OK] [OK]=[OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]j[OK]s[OK]o[OK]n[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]"[OK]r[OK]e[OK]c[OK]e[OK]i[OK]v[OK]e[OK]d[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]✅[OK] [OK]T[OK]A[OK]B[OK]L[OK]E[OK]_[OK]R[OK]E[OK]Q[OK]U[OK]E[OK]S[OK]T[OK] [OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK] [OK]h[OK]a[OK]n[OK]d[OK]l[OK]i[OK]n[OK]g[OK] [OK]w[OK]o[OK]r[OK]k[OK]i[OK]n[OK]g[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]d[OK]e[OK]f[OK] [OK]t[OK]e[OK]s[OK]t[OK]_[OK]t[OK]a[OK]b[OK]l[OK]e[OK]_[OK]m[OK]a[OK]n[OK]a[OK]g[OK]e[OK]m[OK]e[OK]n[OK]t[OK]([OK]s[OK]e[OK]l[OK]f[OK])[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]T[OK]e[OK]s[OK]t[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK] [OK]l[OK]i[OK]s[OK]t[OK]i[OK]n[OK]g[OK] [OK]a[OK]n[OK]d[OK] [OK]m[OK]a[OK]n[OK]a[OK]g[OK]e[OK]m[OK]e[OK]n[OK]t[OK]"[OK]"[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]T[OK]e[OK]s[OK]t[OK]i[OK]n[OK]g[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK] [OK]m[OK]a[OK]n[OK]a[OK]g[OK]e[OK]m[OK]e[OK]n[OK]t[OK].[OK].[OK].[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]T[OK]e[OK]s[OK]t[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK] [OK]l[OK]i[OK]s[OK]t[OK]i[OK]n[OK]g[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]s[OK]e[OK]l[OK]f[OK].[OK]s[OK]e[OK]s[OK]s[OK]i[OK]o[OK]n[OK].[OK]g[OK]e[OK]t[OK]([OK]f[OK]"[OK]{[OK]s[OK]e[OK]l[OK]f[OK].[OK]b[OK]a[OK]s[OK]e[OK]_[OK]u[OK]r[OK]l[OK]}[OK]/[OK]a[OK]p[OK]i[OK]/[OK]t[OK]a[OK]b[OK]l[OK]e[OK]s[OK]"[OK])[OK] [OK]a[OK]s[OK] [OK]r[OK]e[OK]s[OK]p[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK] [OK]=[OK]=[OK] [OK]2[OK]0[OK]0[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]a[OK]t[OK]a[OK] [OK]=[OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]j[OK]s[OK]o[OK]n[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]"[OK]s[OK]u[OK]c[OK]c[OK]e[OK]s[OK]s[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]i[OK]s[OK]i[OK]n[OK]s[OK]t[OK]a[OK]n[OK]c[OK]e[OK]([OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]t[OK]a[OK]b[OK]l[OK]e[OK]s[OK]"[OK]][OK],[OK] [OK]l[OK]i[OK]s[OK]t[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]l[OK]e[OK]n[OK]([OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]t[OK]a[OK]b[OK]l[OK]e[OK]s[OK]"[OK]][OK])[OK] [OK]>[OK]=[OK] [OK]1[OK] [OK] [OK]#[OK] [OK]S[OK]h[OK]o[OK]u[OK]l[OK]d[OK] [OK]h[OK]a[OK]v[OK]e[OK] [OK]a[OK]t[OK] [OK]l[OK]e[OK]a[OK]s[OK]t[OK] [OK]d[OK]e[OK]f[OK]a[OK]u[OK]l[OK]t[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]C[OK]h[OK]e[OK]c[OK]k[OK] [OK]d[OK]e[OK]f[OK]a[OK]u[OK]l[OK]t[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK] [OK]e[OK]x[OK]i[OK]s[OK]t[OK]s[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]e[OK]f[OK]a[OK]u[OK]l[OK]t[OK]_[OK]f[OK]o[OK]u[OK]n[OK]d[OK] [OK]=[OK] [OK]F[OK]a[OK]l[OK]s[OK]e[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK] [OK]i[OK]n[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]t[OK]a[OK]b[OK]l[OK]e[OK]s[OK]"[OK]][OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK][[OK]"[OK]n[OK]a[OK]m[OK]e[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]"[OK]d[OK]e[OK]f[OK]a[OK]u[OK]l[OK]t[OK]"[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]e[OK]f[OK]a[OK]u[OK]l[OK]t[OK]_[OK]f[OK]o[OK]u[OK]n[OK]d[OK] [OK]=[OK] [OK]T[OK]r[OK]u[OK]e[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK][[OK]"[OK]w[OK]i[OK]d[OK]t[OK]h[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]1[OK]0[OK]0[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK][[OK]"[OK]h[OK]e[OK]i[OK]g[OK]h[OK]t[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]1[OK]0[OK]0[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]r[OK]e[OK]a[OK]k[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]e[OK]f[OK]a[OK]u[OK]l[OK]t[OK]_[OK]f[OK]o[OK]u[OK]n[OK]d[OK],[OK] [OK]"[OK]D[OK]e[OK]f[OK]a[OK]u[OK]l[OK]t[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK] [OK]n[OK]o[OK]t[OK] [OK]f[OK]o[OK]u[OK]n[OK]d[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]✅[OK] [OK]T[OK]a[OK]b[OK]l[OK]e[OK] [OK]l[OK]i[OK]s[OK]t[OK]i[OK]n[OK]g[OK] [OK]w[OK]o[OK]r[OK]k[OK]i[OK]n[OK]g[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]T[OK]e[OK]s[OK]t[OK] [OK]s[OK]p[OK]e[OK]c[OK]i[OK]f[OK]i[OK]c[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK] [OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]s[OK]e[OK]l[OK]f[OK].[OK]s[OK]e[OK]s[OK]s[OK]i[OK]o[OK]n[OK].[OK]g[OK]e[OK]t[OK]([OK]f[OK]"[OK]{[OK]s[OK]e[OK]l[OK]f[OK].[OK]b[OK]a[OK]s[OK]e[OK]_[OK]u[OK]r[OK]l[OK]}[OK]/[OK]a[OK]p[OK]i[OK]/[OK]t[OK]a[OK]b[OK]l[OK]e[OK]/[OK]d[OK]e[OK]f[OK]a[OK]u[OK]l[OK]t[OK]"[OK])[OK] [OK]a[OK]s[OK] [OK]r[OK]e[OK]s[OK]p[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK] [OK]=[OK]=[OK] [OK]2[OK]0[OK]0[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]a[OK]t[OK]a[OK] [OK]=[OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]j[OK]s[OK]o[OK]n[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]"[OK]s[OK]u[OK]c[OK]c[OK]e[OK]s[OK]s[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]t[OK]a[OK]b[OK]l[OK]e[OK]"[OK]][OK][[OK]"[OK]n[OK]a[OK]m[OK]e[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]"[OK]d[OK]e[OK]f[OK]a[OK]u[OK]l[OK]t[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]✅[OK] [OK]S[OK]p[OK]e[OK]c[OK]i[OK]f[OK]i[OK]c[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK] [OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK] [OK]w[OK]o[OK]r[OK]k[OK]i[OK]n[OK]g[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]d[OK]e[OK]f[OK] [OK]t[OK]e[OK]s[OK]t[OK]_[OK]t[OK]a[OK]b[OK]l[OK]e[OK]_[OK]c[OK]r[OK]e[OK]a[OK]t[OK]i[OK]o[OK]n[OK]([OK]s[OK]e[OK]l[OK]f[OK])[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]T[OK]e[OK]s[OK]t[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]i[OK]o[OK]n[OK]"[OK]"[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]T[OK]e[OK]s[OK]t[OK]i[OK]n[OK]g[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]i[OK]o[OK]n[OK].[OK].[OK].[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK]_[OK]d[OK]a[OK]t[OK]a[OK] [OK]=[OK] [OK]{[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]n[OK]a[OK]m[OK]e[OK]"[OK]:[OK] [OK]"[OK]t[OK]e[OK]s[OK]t[OK]-[OK]t[OK]a[OK]b[OK]l[OK]e[OK]-[OK]c[OK]o[OK]m[OK]p[OK]r[OK]e[OK]h[OK]e[OK]n[OK]s[OK]i[OK]v[OK]e[OK]"[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]w[OK]i[OK]d[OK]t[OK]h[OK]"[OK]:[OK] [OK]1[OK]5[OK]0[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]h[OK]e[OK]i[OK]g[OK]h[OK]t[OK]"[OK]:[OK] [OK]1[OK]5[OK]0[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]}[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]s[OK]e[OK]l[OK]f[OK].[OK]s[OK]e[OK]s[OK]s[OK]i[OK]o[OK]n[OK].[OK]p[OK]o[OK]s[OK]t[OK]([OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]"[OK]{[OK]s[OK]e[OK]l[OK]f[OK].[OK]b[OK]a[OK]s[OK]e[OK]_[OK]u[OK]r[OK]l[OK]}[OK]/[OK]a[OK]p[OK]i[OK]/[OK]t[OK]a[OK]b[OK]l[OK]e[OK]/[OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]"[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]j[OK]s[OK]o[OK]n[OK]=[OK]t[OK]a[OK]b[OK]l[OK]e[OK]_[OK]d[OK]a[OK]t[OK]a[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK] [OK]a[OK]s[OK] [OK]r[OK]e[OK]s[OK]p[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK] [OK]=[OK]=[OK] [OK]2[OK]0[OK]0[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]a[OK]t[OK]a[OK] [OK]=[OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]j[OK]s[OK]o[OK]n[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]"[OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]t[OK]a[OK]b[OK]l[OK]e[OK]"[OK]][OK][[OK]"[OK]n[OK]a[OK]m[OK]e[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]"[OK]t[OK]e[OK]s[OK]t[OK]-[OK]t[OK]a[OK]b[OK]l[OK]e[OK]-[OK]c[OK]o[OK]m[OK]p[OK]r[OK]e[OK]h[OK]e[OK]n[OK]s[OK]i[OK]v[OK]e[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]t[OK]a[OK]b[OK]l[OK]e[OK]"[OK]][OK][[OK]"[OK]w[OK]i[OK]d[OK]t[OK]h[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]1[OK]5[OK]0[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]t[OK]a[OK]b[OK]l[OK]e[OK]"[OK]][OK][[OK]"[OK]h[OK]e[OK]i[OK]g[OK]h[OK]t[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]1[OK]5[OK]0[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]✅[OK] [OK]T[OK]a[OK]b[OK]l[OK]e[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]i[OK]o[OK]n[OK] [OK]w[OK]o[OK]r[OK]k[OK]i[OK]n[OK]g[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]V[OK]e[OK]r[OK]i[OK]f[OK]y[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK] [OK]w[OK]a[OK]s[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK] [OK]b[OK]y[OK] [OK]l[OK]i[OK]s[OK]t[OK]i[OK]n[OK]g[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK]s[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]s[OK]e[OK]l[OK]f[OK].[OK]s[OK]e[OK]s[OK]s[OK]i[OK]o[OK]n[OK].[OK]g[OK]e[OK]t[OK]([OK]f[OK]"[OK]{[OK]s[OK]e[OK]l[OK]f[OK].[OK]b[OK]a[OK]s[OK]e[OK]_[OK]u[OK]r[OK]l[OK]}[OK]/[OK]a[OK]p[OK]i[OK]/[OK]t[OK]a[OK]b[OK]l[OK]e[OK]s[OK]"[OK])[OK] [OK]a[OK]s[OK] [OK]r[OK]e[OK]s[OK]p[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK] [OK]=[OK]=[OK] [OK]2[OK]0[OK]0[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]a[OK]t[OK]a[OK] [OK]=[OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]j[OK]s[OK]o[OK]n[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]e[OK]s[OK]t[OK]_[OK]t[OK]a[OK]b[OK]l[OK]e[OK]_[OK]f[OK]o[OK]u[OK]n[OK]d[OK] [OK]=[OK] [OK]F[OK]a[OK]l[OK]s[OK]e[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK] [OK]i[OK]n[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]t[OK]a[OK]b[OK]l[OK]e[OK]s[OK]"[OK]][OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK][[OK]"[OK]n[OK]a[OK]m[OK]e[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]"[OK]t[OK]e[OK]s[OK]t[OK]-[OK]t[OK]a[OK]b[OK]l[OK]e[OK]-[OK]c[OK]o[OK]m[OK]p[OK]r[OK]e[OK]h[OK]e[OK]n[OK]s[OK]i[OK]v[OK]e[OK]"[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]e[OK]s[OK]t[OK]_[OK]t[OK]a[OK]b[OK]l[OK]e[OK]_[OK]f[OK]o[OK]u[OK]n[OK]d[OK] [OK]=[OK] [OK]T[OK]r[OK]u[OK]e[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]r[OK]e[OK]a[OK]k[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]t[OK]e[OK]s[OK]t[OK]_[OK]t[OK]a[OK]b[OK]l[OK]e[OK]_[OK]f[OK]o[OK]u[OK]n[OK]d[OK],[OK] [OK]"[OK]C[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK] [OK]n[OK]o[OK]t[OK] [OK]f[OK]o[OK]u[OK]n[OK]d[OK] [OK]i[OK]n[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK] [OK]l[OK]i[OK]s[OK]t[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]✅[OK] [OK]T[OK]a[OK]b[OK]l[OK]e[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]i[OK]o[OK]n[OK] [OK]v[OK]e[OK]r[OK]i[OK]f[OK]i[OK]c[OK]a[OK]t[OK]i[OK]o[OK]n[OK] [OK]w[OK]o[OK]r[OK]k[OK]i[OK]n[OK]g[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]d[OK]e[OK]f[OK] [OK]t[OK]e[OK]s[OK]t[OK]_[OK]p[OK]i[OK]n[OK]g[OK]_[OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK]([OK]s[OK]e[OK]l[OK]f[OK],[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK]:[OK] [OK]s[OK]t[OK]r[OK])[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]T[OK]e[OK]s[OK]t[OK] [OK]p[OK]i[OK]n[OK]g[OK] [OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK]"[OK]"[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]T[OK]e[OK]s[OK]t[OK]i[OK]n[OK]g[OK] [OK]p[OK]i[OK]n[OK]g[OK] [OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK].[OK].[OK].[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]i[OK]n[OK]g[OK]_[OK]d[OK]a[OK]t[OK]a[OK] [OK]=[OK] [OK]{[OK]"[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK]"[OK]:[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK]}[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]s[OK]e[OK]l[OK]f[OK].[OK]s[OK]e[OK]s[OK]s[OK]i[OK]o[OK]n[OK].[OK]p[OK]o[OK]s[OK]t[OK]([OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]"[OK]{[OK]s[OK]e[OK]l[OK]f[OK].[OK]b[OK]a[OK]s[OK]e[OK]_[OK]u[OK]r[OK]l[OK]}[OK]/[OK]a[OK]p[OK]i[OK]/[OK]p[OK]i[OK]n[OK]g[OK]"[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]j[OK]s[OK]o[OK]n[OK]=[OK]p[OK]i[OK]n[OK]g[OK]_[OK]d[OK]a[OK]t[OK]a[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK] [OK]a[OK]s[OK] [OK]r[OK]e[OK]s[OK]p[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK] [OK]=[OK]=[OK] [OK]2[OK]0[OK]0[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]a[OK]t[OK]a[OK] [OK]=[OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]j[OK]s[OK]o[OK]n[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]"[OK]p[OK]o[OK]n[OK]g[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]✅[OK] [OK]P[OK]i[OK]n[OK]g[OK] [OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK] [OK]w[OK]o[OK]r[OK]k[OK]i[OK]n[OK]g[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]d[OK]e[OK]f[OK] [OK]t[OK]e[OK]s[OK]t[OK]_[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]u[OK]n[OK]r[OK]e[OK]g[OK]i[OK]s[OK]t[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK]([OK]s[OK]e[OK]l[OK]f[OK],[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK]:[OK] [OK]s[OK]t[OK]r[OK])[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]T[OK]e[OK]s[OK]t[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK] [OK]u[OK]n[OK]r[OK]e[OK]g[OK]i[OK]s[OK]t[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK]"[OK]"[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]T[OK]e[OK]s[OK]t[OK]i[OK]n[OK]g[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK] [OK]u[OK]n[OK]r[OK]e[OK]g[OK]i[OK]s[OK]t[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK].[OK].[OK].[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]u[OK]n[OK]r[OK]e[OK]g[OK]i[OK]s[OK]t[OK]e[OK]r[OK]_[OK]d[OK]a[OK]t[OK]a[OK] [OK]=[OK] [OK]{[OK]"[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK]"[OK]:[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK]}[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]s[OK]e[OK]l[OK]f[OK].[OK]s[OK]e[OK]s[OK]s[OK]i[OK]o[OK]n[OK].[OK]p[OK]o[OK]s[OK]t[OK]([OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]"[OK]{[OK]s[OK]e[OK]l[OK]f[OK].[OK]b[OK]a[OK]s[OK]e[OK]_[OK]u[OK]r[OK]l[OK]}[OK]/[OK]a[OK]p[OK]i[OK]/[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]/[OK]u[OK]n[OK]r[OK]e[OK]g[OK]i[OK]s[OK]t[OK]e[OK]r[OK]"[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]j[OK]s[OK]o[OK]n[OK]=[OK]u[OK]n[OK]r[OK]e[OK]g[OK]i[OK]s[OK]t[OK]e[OK]r[OK]_[OK]d[OK]a[OK]t[OK]a[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK] [OK]a[OK]s[OK] [OK]r[OK]e[OK]s[OK]p[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK] [OK]=[OK]=[OK] [OK]2[OK]0[OK]0[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]a[OK]t[OK]a[OK] [OK]=[OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]j[OK]s[OK]o[OK]n[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]"[OK]u[OK]n[OK]r[OK]e[OK]g[OK]i[OK]s[OK]t[OK]e[OK]r[OK]e[OK]d[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]✅[OK] [OK]C[OK]l[OK]i[OK]e[OK]n[OK]t[OK] [OK]u[OK]n[OK]r[OK]e[OK]g[OK]i[OK]s[OK]t[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK] [OK]w[OK]o[OK]r[OK]k[OK]i[OK]n[OK]g[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]V[OK]e[OK]r[OK]i[OK]f[OK]y[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK] [OK]w[OK]a[OK]s[OK] [OK]r[OK]e[OK]m[OK]o[OK]v[OK]e[OK]d[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]s[OK]e[OK]l[OK]f[OK].[OK]s[OK]e[OK]s[OK]s[OK]i[OK]o[OK]n[OK].[OK]g[OK]e[OK]t[OK]([OK]f[OK]"[OK]{[OK]s[OK]e[OK]l[OK]f[OK].[OK]b[OK]a[OK]s[OK]e[OK]_[OK]u[OK]r[OK]l[OK]}[OK]/[OK]a[OK]p[OK]i[OK]/[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]s[OK]"[OK])[OK] [OK]a[OK]s[OK] [OK]r[OK]e[OK]s[OK]p[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK] [OK]=[OK]=[OK] [OK]2[OK]0[OK]0[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]a[OK]t[OK]a[OK] [OK]=[OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]j[OK]s[OK]o[OK]n[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]f[OK]o[OK]u[OK]n[OK]d[OK] [OK]=[OK] [OK]F[OK]a[OK]l[OK]s[OK]e[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK] [OK]i[OK]n[OK] [OK]d[OK]a[OK]t[OK]a[OK][[OK]"[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]s[OK]"[OK]][OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK][[OK]"[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK]"[OK]][OK] [OK]=[OK]=[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]f[OK]o[OK]u[OK]n[OK]d[OK] [OK]=[OK] [OK]T[OK]r[OK]u[OK]e[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]r[OK]e[OK]a[OK]k[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]s[OK]s[OK]e[OK]r[OK]t[OK] [OK]n[OK]o[OK]t[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]f[OK]o[OK]u[OK]n[OK]d[OK],[OK] [OK]"[OK]U[OK]n[OK]r[OK]e[OK]g[OK]i[OK]s[OK]t[OK]e[OK]r[OK]e[OK]d[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK] [OK]s[OK]t[OK]i[OK]l[OK]l[OK] [OK]f[OK]o[OK]u[OK]n[OK]d[OK] [OK]i[OK]n[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK] [OK]l[OK]i[OK]s[OK]t[OK]"[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]✅[OK] [OK]C[OK]l[OK]i[OK]e[OK]n[OK]t[OK] [OK]u[OK]n[OK]r[OK]e[OK]g[OK]i[OK]s[OK]t[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK] [OK]v[OK]e[OK]r[OK]i[OK]f[OK]i[OK]c[OK]a[OK]t[OK]i[OK]o[OK]n[OK] [OK]w[OK]o[OK]r[OK]k[OK]i[OK]n[OK]g[OK]"[OK])[OK]
[OK]
[OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]d[OK]e[OK]f[OK] [OK]r[OK]u[OK]n[OK]_[OK]c[OK]o[OK]m[OK]p[OK]r[OK]e[OK]h[OK]e[OK]n[OK]s[OK]i[OK]v[OK]e[OK]_[OK]t[OK]e[OK]s[OK]t[OK]([OK])[OK]:[OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]R[OK]u[OK]n[OK] [OK]a[OK]l[OK]l[OK] [OK]c[OK]o[OK]m[OK]p[OK]r[OK]e[OK]h[OK]e[OK]n[OK]s[OK]i[OK]v[OK]e[OK] [OK]t[OK]e[OK]s[OK]t[OK]s[OK]"[OK]"[OK]"[OK]
[OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]S[OK]t[OK]a[OK]r[OK]t[OK]i[OK]n[OK]g[OK] [OK]c[OK]o[OK]m[OK]p[OK]r[OK]e[OK]h[OK]e[OK]n[OK]s[OK]i[OK]v[OK]e[OK] [OK]s[OK]e[OK]r[OK]v[OK]e[OK]r[OK] [OK]t[OK]e[OK]s[OK]t[OK].[OK].[OK].[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]S[OK]e[OK]r[OK]v[OK]e[OK]r[OK]T[OK]e[OK]s[OK]t[OK]e[OK]r[OK]([OK])[OK] [OK]a[OK]s[OK] [OK]t[OK]e[OK]s[OK]t[OK]e[OK]r[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]r[OK]y[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]T[OK]e[OK]s[OK]t[OK] [OK]s[OK]e[OK]r[OK]v[OK]e[OK]r[OK] [OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]t[OK]e[OK]s[OK]t[OK]e[OK]r[OK].[OK]t[OK]e[OK]s[OK]t[OK]_[OK]s[OK]e[OK]r[OK]v[OK]e[OK]r[OK]_[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]T[OK]e[OK]s[OK]t[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK] [OK]r[OK]e[OK]g[OK]i[OK]s[OK]t[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK] [OK]=[OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]t[OK]e[OK]s[OK]t[OK]e[OK]r[OK].[OK]t[OK]e[OK]s[OK]t[OK]_[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]r[OK]e[OK]g[OK]i[OK]s[OK]t[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]T[OK]e[OK]s[OK]t[OK] [OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK] [OK]h[OK]a[OK]n[OK]d[OK]l[OK]i[OK]n[OK]g[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]t[OK]e[OK]s[OK]t[OK]e[OK]r[OK].[OK]t[OK]e[OK]s[OK]t[OK]_[OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK]_[OK]h[OK]a[OK]n[OK]d[OK]l[OK]i[OK]n[OK]g[OK]([OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]T[OK]e[OK]s[OK]t[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK] [OK]m[OK]a[OK]n[OK]a[OK]g[OK]e[OK]m[OK]e[OK]n[OK]t[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]t[OK]e[OK]s[OK]t[OK]e[OK]r[OK].[OK]t[OK]e[OK]s[OK]t[OK]_[OK]t[OK]a[OK]b[OK]l[OK]e[OK]_[OK]m[OK]a[OK]n[OK]a[OK]g[OK]e[OK]m[OK]e[OK]n[OK]t[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]T[OK]e[OK]s[OK]t[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]i[OK]o[OK]n[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]t[OK]e[OK]s[OK]t[OK]e[OK]r[OK].[OK]t[OK]e[OK]s[OK]t[OK]_[OK]t[OK]a[OK]b[OK]l[OK]e[OK]_[OK]c[OK]r[OK]e[OK]a[OK]t[OK]i[OK]o[OK]n[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]T[OK]e[OK]s[OK]t[OK] [OK]p[OK]i[OK]n[OK]g[OK] [OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]t[OK]e[OK]s[OK]t[OK]e[OK]r[OK].[OK]t[OK]e[OK]s[OK]t[OK]_[OK]p[OK]i[OK]n[OK]g[OK]_[OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK]([OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]T[OK]e[OK]s[OK]t[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK] [OK]u[OK]n[OK]r[OK]e[OK]g[OK]i[OK]s[OK]t[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]t[OK]e[OK]s[OK]t[OK]e[OK]r[OK].[OK]t[OK]e[OK]s[OK]t[OK]_[OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]u[OK]n[OK]r[OK]e[OK]g[OK]i[OK]s[OK]t[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK]([OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]_[OK]i[OK]d[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]A[OK]L[OK]L[OK] [OK]T[OK]E[OK]S[OK]T[OK]S[OK] [OK]P[OK]A[OK]S[OK]S[OK]E[OK]D[OK]![OK] [OK]S[OK]e[OK]r[OK]v[OK]e[OK]r[OK] [OK]i[OK]s[OK] [OK]f[OK]u[OK]l[OK]l[OK]y[OK] [OK]f[OK]u[OK]n[OK]c[OK]t[OK]i[OK]o[OK]n[OK]a[OK]l[OK].[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]T[OK]r[OK]u[OK]e[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]e[OK]x[OK]c[OK]e[OK]p[OK]t[OK] [OK]E[OK]x[OK]c[OK]e[OK]p[OK]t[OK]i[OK]o[OK]n[OK] [OK]a[OK]s[OK] [OK]e[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]e[OK]r[OK]r[OK]o[OK]r[OK]([OK]f[OK]"[OK]T[OK]E[OK]S[OK]T[OK] [OK]F[OK]A[OK]I[OK]L[OK]E[OK]D[OK]:[OK] [OK]{[OK]e[OK]}[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]t[OK]r[OK]a[OK]c[OK]e[OK]b[OK]a[OK]c[OK]k[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]r[OK]a[OK]c[OK]e[OK]b[OK]a[OK]c[OK]k[OK].[OK]p[OK]r[OK]i[OK]n[OK]t[OK]_[OK]e[OK]x[OK]c[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]F[OK]a[OK]l[OK]s[OK]e[OK]
[OK]
[OK]i[OK]f[OK] [OK]_[OK]_[OK]n[OK]a[OK]m[OK]e[OK]_[OK]_[OK] [OK]=[OK]=[OK] [OK]"[OK]_[OK]_[OK]m[OK]a[OK]i[OK]n[OK]_[OK]_[OK]"[OK]:[OK]
[OK] [OK] [OK] [OK] [OK]s[OK]u[OK]c[OK]c[OK]e[OK]s[OK]s[OK] [OK]=[OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK]i[OK]o[OK].[OK]r[OK]u[OK]n[OK]([OK]r[OK]u[OK]n[OK]_[OK]c[OK]o[OK]m[OK]p[OK]r[OK]e[OK]h[OK]e[OK]n[OK]s[OK]i[OK]v[OK]e[OK]_[OK]t[OK]e[OK]s[OK]t[OK]([OK])[OK])[OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]s[OK]u[OK]c[OK]c[OK]e[OK]s[OK]s[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]C[OK]o[OK]m[OK]p[OK]r[OK]e[OK]h[OK]e[OK]n[OK]s[OK]i[OK]v[OK]e[OK] [OK]t[OK]e[OK]s[OK]t[OK] [OK]c[OK]o[OK]m[OK]p[OK]l[OK]e[OK]t[OK]e[OK]d[OK] [OK]s[OK]u[OK]c[OK]c[OK]e[OK]s[OK]s[OK]f[OK]u[OK]l[OK]l[OK]y[OK]![OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]S[OK]e[OK]r[OK]v[OK]e[OK]r[OK] [OK]i[OK]s[OK] [OK]r[OK]e[OK]a[OK]d[OK]y[OK] [OK]f[OK]o[OK]r[OK] [OK]p[OK]r[OK]o[OK]d[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]d[OK]e[OK]p[OK]l[OK]o[OK]y[OK]m[OK]e[OK]n[OK]t[OK] [OK]t[OK]o[OK] [OK]r[OK]e[OK]n[OK]d[OK]e[OK]r[OK].[OK]c[OK]o[OK]m[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK]e[OK]l[OK]s[OK]e[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]T[OK]e[OK]s[OK]t[OK]s[OK] [OK]f[OK]a[OK]i[OK]l[OK]e[OK]d[OK].[OK] [OK]C[OK]h[OK]e[OK]c[OK]k[OK] [OK]t[OK]h[OK]e[OK] [OK]l[OK]o[OK]g[OK]s[OK] [OK]a[OK]b[OK]o[OK]v[OK]e[OK] [OK]f[OK]o[OK]r[OK] [OK]d[OK]e[OK]t[OK]a[OK]i[OK]l[OK]s[OK].[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]e[OK]x[OK]i[OK]t[OK]([OK]1[OK])[OK]
