import { vi } from 'vitest';

// Creates a mock RenderEngine with all required methods as vi.fn()
export function createMockRenderEngine() {
  return {
    free: vi.fn(),
    render: vi.fn(),
    resize_canvas: vi.fn(),
    resize: vi.fn(),
    // Visibility / geometry
    compute_visibility_polygon: vi.fn().mockReturnValue([]),
    // Fog polygons (dynamic vision)
    add_fog_polygon: vi.fn(),
    remove_fog_polygon: vi.fn(),
    set_ambient_light: vi.fn(),
    set_dynamic_lighting_enabled: vi.fn(),
    // Camera
    handle_wheel: vi.fn(),
    set_zoom: vi.fn(),
    center_camera: vi.fn(),
    set_camera: vi.fn(),
    set_camera_position: vi.fn(),
    set_camera_scale: vi.fn(),
    reset_camera: vi.fn(),
    screen_to_world: vi.fn().mockReturnValue(new Float64Array([0, 0])),
    world_to_screen: vi.fn().mockReturnValue(new Float64Array([0, 0])),
    get_viewport_bounds: vi.fn().mockReturnValue(new Float64Array([0, 0, 800, 600])),
    get_active_table_world_bounds: vi.fn().mockReturnValue(new Float64Array([0, 0, 800, 600])),
    // Input
    get_cursor_type: vi.fn().mockReturnValue('default'),
    handle_mouse_down: vi.fn(),
    handle_mouse_down_with_ctrl: vi.fn(),
    handle_mouse_move: vi.fn(),
    handle_mouse_up: vi.fn(),
    handle_right_click: vi.fn().mockReturnValue(undefined),
    // Input modes
    get_current_input_mode: vi.fn().mockReturnValue('select'),
    set_input_mode_measurement: vi.fn(),
    set_input_mode_create_rectangle: vi.fn(),
    set_input_mode_create_circle: vi.fn(),
    set_input_mode_create_line: vi.fn(),
    set_input_mode_create_text: vi.fn(),
    set_input_mode_select: vi.fn(),
    set_input_mode_paint: vi.fn(),
    set_input_mode_draw_wall: vi.fn(),
    set_input_mode_create_polygon: vi.fn(),
    cancel_polygon_creation: vi.fn(),
    // Sprites
    add_sprite_to_layer: vi.fn().mockReturnValue('sprite_mock_id'),
    remove_sprite: vi.fn().mockReturnValue(true),
    delete_sprite: vi.fn().mockReturnValue(true),
    rotate_sprite: vi.fn().mockReturnValue(true),
    resize_sprite: vi.fn().mockReturnValue(true),
    copy_sprite: vi.fn().mockReturnValue('sprite_copy_id'),
    paste_sprite: vi.fn().mockReturnValue('sprite_paste_id'),
    // Grid
    toggle_grid: vi.fn(),
    set_grid_enabled: vi.fn(),
    toggle_grid_snapping: vi.fn(),
    set_grid_snapping: vi.fn(),
    set_snap_to_grid: vi.fn(),
    set_grid_size: vi.fn(),
    get_grid_size: vi.fn().mockReturnValue(50),
    is_grid_snapping_enabled: vi.fn().mockReturnValue(false),
    set_grid_color: vi.fn(),
    set_background_color: vi.fn(),
    // Textures
    load_texture: vi.fn(),
    // Lighting
    add_light: vi.fn(),
    remove_light: vi.fn(),
    set_light_color: vi.fn(),
    set_light_intensity: vi.fn(),
    set_light_radius: vi.fn(),
    get_light_radius: vi.fn().mockReturnValue(200),
    toggle_light: vi.fn(),
    update_light_position: vi.fn(),
    turn_on_all_lights: vi.fn(),
    turn_off_all_lights: vi.fn(),
    get_light_count: vi.fn().mockReturnValue(0),
    clear_lights: vi.fn(),
    get_light_at_position: vi.fn().mockReturnValue(undefined),
    start_light_drag: vi.fn().mockReturnValue(false),
    update_light_drag: vi.fn().mockReturnValue(false),
    end_light_drag: vi.fn().mockReturnValue(undefined),
    set_light_drag_mode: vi.fn(),
    is_in_light_drag_mode: vi.fn().mockReturnValue(false),
    // Fog rectangles
    add_fog_rectangle: vi.fn(),
    remove_fog_rectangle: vi.fn(),
    clear_fog: vi.fn(),
    hide_entire_table: vi.fn(),
    is_point_in_fog: vi.fn().mockReturnValue(false),
    get_fog_count: vi.fn().mockReturnValue(0),
    get_fog_at_position: vi.fn().mockReturnValue(undefined),
    start_fog_draw: vi.fn().mockReturnValue('fog_draw_id'),
    update_fog_draw: vi.fn().mockReturnValue(true),
    finish_fog_draw: vi.fn().mockReturnValue(true),
    cancel_fog_draw: vi.fn(),
    set_fog_draw_mode: vi.fn(),
    set_fog_erase_mode: vi.fn(),
    is_in_fog_draw_mode: vi.fn().mockReturnValue(false),
    // GM / user
    set_gm_mode: vi.fn(),
    set_current_user_id: vi.fn(),
    // Metrics
    get_performance_metrics: vi.fn().mockReturnValue({ fps: 60, sprite_count: 0, render_time_ms: 16 }),
  };
}
