/**
 * Message protocol definitions matching Python protocol.py exactly
 * Ensures compatibility with server-side message handling
 */

import Ajv2020 from 'ajv/dist/2020';

import messageSchema from './message.schema.generated.json';

// BEGIN GENERATED MESSAGE TYPES - run packages/core-table/scripts/generate_protocol_types.py
export const MessageType = {
  PING: "ping",
  PONG: "pong",
  ERROR: "error",
  TEST: "test",
  SUCCESS: "success",
  WELCOME: "welcome",
  NEW_TABLE_REQUEST: "new_table_request",
  NEW_TABLE_RESPONSE: "new_table_response",
  TABLE_REQUEST: "table_request",
  TABLE_RESPONSE: "table_response",
  TABLE_DATA: "table_data",
  TABLE_UPDATE_REQUEST: "table_update_request",
  TABLE_UPDATE: "table_update",
  TABLE_SCALE: "table_scale",
  TABLE_MOVE: "table_move",
  TABLE_LIST_REQUEST: "table_list_request",
  TABLE_LIST_RESPONSE: "table_list_response",
  TABLE_DELETE: "table_delete",
  TABLE_ACTIVE_REQUEST: "table_active_request",
  TABLE_ACTIVE_RESPONSE: "table_active_response",
  TABLE_ACTIVE_SET: "table_active_set",
  TABLE_ACTIVE_SET_ALL: "table_active_set_all",
  TABLE_ACTIVE_SET_ALL_RESPONSE: "table_active_set_all_response",
  PLAYER_LEFT: "player_left",
  PLAYER_JOINED: "player_joined",
  PLAYER_READY: "player_ready",
  PLAYER_UNREADY: "player_unready",
  PLAYER_STATUS_REQUEST: "player_status_request",
  PLAYER_STATUS_RESPONSE: "player_status_response",
  PLAYER_STATUS_CHANGED: "player_status_changed",
  PLAYER_LIST_REQUEST: "player_list_request",
  PLAYER_LIST_RESPONSE: "player_list_response",
  PLAYER_KICK_REQUEST: "player_kick_request",
  PLAYER_BAN_REQUEST: "player_ban_request",
  PLAYER_KICK_RESPONSE: "player_kick_response",
  PLAYER_BAN_RESPONSE: "player_ban_response",
  PLAYER_ROLE_CHANGED: "player_role_changed",
  CONNECTION_STATUS_REQUEST: "connection_status_request",
  CONNECTION_STATUS_RESPONSE: "connection_status_response",
  SPRITE_REQUEST: "sprite_request",
  SPRITE_RESPONSE: "sprite_response",
  SPRITE_DATA: "sprite_data",
  SPRITE_UPDATE: "sprite_update",
  SPRITE_REMOVE: "sprite_remove",
  SPRITE_CREATE: "sprite_create",
  SPRITE_MOVE: "sprite_move",
  SPRITE_SCALE: "sprite_scale",
  SPRITE_ROTATE: "sprite_rotate",
  SPRITE_DRAG_PREVIEW: "sprite_drag_preview",
  SPRITE_RESIZE_PREVIEW: "sprite_resize_preview",
  SPRITE_ROTATE_PREVIEW: "sprite_rotate_preview",
  FILE_REQUEST: "file_request",
  FILE_DATA: "file_data",
  ASSET_UPLOAD_REQUEST: "asset_upload_request",
  ASSET_UPLOAD_RESPONSE: "asset_upload_response",
  ASSET_DOWNLOAD_REQUEST: "asset_download_request",
  ASSET_DOWNLOAD_RESPONSE: "asset_download_response",
  ASSET_LIST_REQUEST: "asset_list_request",
  ASSET_LIST_RESPONSE: "asset_list_response",
  ASSET_UPLOAD_CONFIRM: "asset_upload_confirm",
  ASSET_DELETE_REQUEST: "asset_delete_request",
  ASSET_DELETE_RESPONSE: "asset_delete_response",
  ASSET_HASH_CHECK: "asset_hash_check",
  COMPENDIUM_SPRITE_ADD: "compendium_sprite_add",
  COMPENDIUM_SPRITE_UPDATE: "compendium_sprite_update",
  COMPENDIUM_SPRITE_REMOVE: "compendium_sprite_remove",
  CHARACTER_SAVE_REQUEST: "character_save_request",
  CHARACTER_SAVE_RESPONSE: "character_save_response",
  GAME_MODE_CHANGE: "game_mode_change",
  GAME_MODE_STATE: "game_mode_state",
  SESSION_RULES_UPDATE: "session_rules_update",
  SESSION_RULES_CHANGED: "session_rules_changed",
  SESSION_RULES_REQUEST: "session_rules_request",
  PLAN_START: "plan_start",
  PLAN_ACK: "plan_ack",
  COMBAT_COMMAND: "combat_command",
  ACTION_RESULT: "action_result",
  ACTION_REJECTED: "action_rejected",
  STATE_SYNC_REQUEST: "state_sync_request",
  STATE_SYNC_RESPONSE: "state_sync_response",
  COMBAT_STATE: "combat_state",
  COMBAT_STATE_REQUEST: "combat_state_request",
  INITIATIVE_ROLL_RESULT: "initiative_roll_result",
  INITIATIVE_ORDER: "initiative_order",
  TURN_START: "turn_start",
  ROUND_START: "round_start",
  ROUND_END: "round_end",
  EXPLORE_SUBMIT: "explore_submit",
  EXPLORE_ROUND_RESOLVE: "explore_round_resolve",
  EXPLORE_ROUND_RESULT: "explore_round_result",
  CONDITION_UPDATE: "condition_update",
  CONDITIONS_SYNC: "conditions_sync",
  DM_OVERRIDE: "dm_override",
  DM_MODIFY_ROLL: "dm_modify_roll",
  AI_ACTION: "ai_action",
  AI_SUGGESTION: "ai_suggestion",
  AI_CONFIG: "ai_config",
  ENCOUNTER_START: "encounter_start",
  ENCOUNTER_END: "encounter_end",
  ENCOUNTER_CHOICE: "encounter_choice",
  ENCOUNTER_ROLL: "encounter_roll",
  ENCOUNTER_RESULT: "encounter_result",
  ENCOUNTER_STATE: "encounter_state",
  CONCENTRATION_BROKEN: "concentration_broken",
  TERRAIN_ZONE_ADD: "terrain_zone_add",
  TERRAIN_ZONE_REMOVE: "terrain_zone_remove",
  TERRAIN_ZONE_UPDATE: "terrain_zone_update",
  TERRAIN_ZONES_SYNC: "terrain_zones_sync",
  COVER_ZONES_SYNC: "cover_zones_sync",
  COMBAT_ABILITY: "combat_ability",
  COMBAT_READY: "combat_ready",
  READY_TRIGGER_FIRE: "ready_trigger_fire",
  CONCENTRATION_SAVED: "concentration_saved",
  OPPORTUNITY_ATTACK_WARNING: "opportunity_attack_warning",
  OPPORTUNITY_ATTACK_PROMPT: "opportunity_attack_prompt",
  ATTACK_PREVIEW: "attack_preview",
  ATTACK_PREVIEW_RESULT: "attack_preview_result",
  TURN_SKIPPED: "turn_skipped",
  SPELL_SLOT_USE: "spell_slot_use",
  RESOURCE_UPDATE: "resource_update",
  REST_SHORT: "rest_short",
  REST_LONG: "rest_long",
  CHARACTER_LOAD_REQUEST: "character_load_request",
  CHARACTER_LOAD_RESPONSE: "character_load_response",
  CHARACTER_LIST_REQUEST: "character_list_request",
  CHARACTER_LIST_RESPONSE: "character_list_response",
  CHARACTER_DELETE_REQUEST: "character_delete_request",
  CHARACTER_DELETE_RESPONSE: "character_delete_response",
  CHARACTER_UPDATE: "character_update",
  CHARACTER_UPDATE_RESPONSE: "character_update_response",
  CHARACTER_LOG_REQUEST: "character_log_request",
  CHARACTER_LOG_RESPONSE: "character_log_response",
  CHARACTER_ROLL: "character_roll",
  CHARACTER_ROLL_RESULT: "character_roll_result",
  CHARACTER_DRAFT_CREATE_REQUEST: "character_draft_create_request",
  CHARACTER_DRAFT_CREATE_RESPONSE: "character_draft_create_response",
  CHARACTER_DRAFT_LIST_REQUEST: "character_draft_list_request",
  CHARACTER_DRAFT_LIST_RESPONSE: "character_draft_list_response",
  CHARACTER_DRAFT_LOAD_REQUEST: "character_draft_load_request",
  CHARACTER_DRAFT_LOAD_RESPONSE: "character_draft_load_response",
  CHARACTER_DRAFT_UPDATE_REQUEST: "character_draft_update_request",
  CHARACTER_DRAFT_UPDATE_RESPONSE: "character_draft_update_response",
  CHARACTER_DRAFT_FINALIZE_REQUEST: "character_draft_finalize_request",
  CHARACTER_DRAFT_FINALIZE_RESPONSE: "character_draft_finalize_response",
  CHARACTER_DRAFT_ABANDON_REQUEST: "character_draft_abandon_request",
  CHARACTER_DRAFT_ABANDON_RESPONSE: "character_draft_abandon_response",
  CHARACTER_DRAFT_UPDATED: "character_draft_updated",
  XP_AWARD: "xp_award",
  XP_AWARD_RESPONSE: "xp_award_response",
  MULTICLASS_REQUEST: "multiclass_request",
  MULTICLASS_RESPONSE: "multiclass_response",
  BATCH_REQUEST: "batch_request",
  BATCH_RESPONSE: "batch_response",
  TABLE_SETTINGS_UPDATE: "table_settings_update",
  TABLE_SETTINGS_CHANGED: "table_settings_changed",
  WALL_CREATE: "wall_create",
  WALL_UPDATE: "wall_update",
  WALL_REMOVE: "wall_remove",
  WALL_BATCH_CREATE: "wall_batch_create",
  WALL_DATA: "wall_data",
  DOOR_TOGGLE: "door_toggle",
  PAINT_STROKE_CREATE: "paint_stroke_create",
  PAINT_STROKE_DELETE: "paint_stroke_delete",
  PAINT_STROKE_CLEAR: "paint_stroke_clear",
  PAINT_SYNC: "paint_sync",
  PAINT_TEMPLATE_UPSERT: "paint_template_upsert",
  PAINT_TEMPLATE_DELETE: "paint_template_delete",
  PAINT_TEMPLATE_SYNC: "paint_template_sync",
  MEASUREMENT_UPSERT: "measurement_upsert",
  MEASUREMENT_DELETE: "measurement_delete",
  MEASUREMENT_CLEAR: "measurement_clear",
  MEASUREMENT_SYNC: "measurement_sync",
  LAYER_SETTINGS_UPDATE: "layer_settings_update",
  CHAT: "chat",
  CHAT_CONFIRMATION: "chat_confirmation",
  CHAT_REQUEST: "chat_request",
  CHAT_MODERATE: "chat_moderate",
  CHAT_MODERATION: "chat_moderation",
  CUSTOM: "custom",
} as const;

export type MessageType = typeof MessageType[keyof typeof MessageType];

export const MESSAGE_TYPE_VALUES = [
  "ping",
  "pong",
  "error",
  "test",
  "success",
  "welcome",
  "new_table_request",
  "new_table_response",
  "table_request",
  "table_response",
  "table_data",
  "table_update_request",
  "table_update",
  "table_scale",
  "table_move",
  "table_list_request",
  "table_list_response",
  "table_delete",
  "table_active_request",
  "table_active_response",
  "table_active_set",
  "table_active_set_all",
  "table_active_set_all_response",
  "player_left",
  "player_joined",
  "player_ready",
  "player_unready",
  "player_status_request",
  "player_status_response",
  "player_status_changed",
  "player_list_request",
  "player_list_response",
  "player_kick_request",
  "player_ban_request",
  "player_kick_response",
  "player_ban_response",
  "player_role_changed",
  "connection_status_request",
  "connection_status_response",
  "sprite_request",
  "sprite_response",
  "sprite_data",
  "sprite_update",
  "sprite_remove",
  "sprite_create",
  "sprite_move",
  "sprite_scale",
  "sprite_rotate",
  "sprite_drag_preview",
  "sprite_resize_preview",
  "sprite_rotate_preview",
  "file_request",
  "file_data",
  "asset_upload_request",
  "asset_upload_response",
  "asset_download_request",
  "asset_download_response",
  "asset_list_request",
  "asset_list_response",
  "asset_upload_confirm",
  "asset_delete_request",
  "asset_delete_response",
  "asset_hash_check",
  "compendium_sprite_add",
  "compendium_sprite_update",
  "compendium_sprite_remove",
  "character_save_request",
  "character_save_response",
  "game_mode_change",
  "game_mode_state",
  "session_rules_update",
  "session_rules_changed",
  "session_rules_request",
  "plan_start",
  "plan_ack",
  "combat_command",
  "action_result",
  "action_rejected",
  "state_sync_request",
  "state_sync_response",
  "combat_state",
  "combat_state_request",
  "initiative_roll_result",
  "initiative_order",
  "turn_start",
  "round_start",
  "round_end",
  "explore_submit",
  "explore_round_resolve",
  "explore_round_result",
  "condition_update",
  "conditions_sync",
  "dm_override",
  "dm_modify_roll",
  "ai_action",
  "ai_suggestion",
  "ai_config",
  "encounter_start",
  "encounter_end",
  "encounter_choice",
  "encounter_roll",
  "encounter_result",
  "encounter_state",
  "concentration_broken",
  "terrain_zone_add",
  "terrain_zone_remove",
  "terrain_zone_update",
  "terrain_zones_sync",
  "cover_zones_sync",
  "combat_ability",
  "combat_ready",
  "ready_trigger_fire",
  "concentration_saved",
  "opportunity_attack_warning",
  "opportunity_attack_prompt",
  "attack_preview",
  "attack_preview_result",
  "turn_skipped",
  "spell_slot_use",
  "resource_update",
  "rest_short",
  "rest_long",
  "character_load_request",
  "character_load_response",
  "character_list_request",
  "character_list_response",
  "character_delete_request",
  "character_delete_response",
  "character_update",
  "character_update_response",
  "character_log_request",
  "character_log_response",
  "character_roll",
  "character_roll_result",
  "character_draft_create_request",
  "character_draft_create_response",
  "character_draft_list_request",
  "character_draft_list_response",
  "character_draft_load_request",
  "character_draft_load_response",
  "character_draft_update_request",
  "character_draft_update_response",
  "character_draft_finalize_request",
  "character_draft_finalize_response",
  "character_draft_abandon_request",
  "character_draft_abandon_response",
  "character_draft_updated",
  "xp_award",
  "xp_award_response",
  "multiclass_request",
  "multiclass_response",
  "batch_request",
  "batch_response",
  "table_settings_update",
  "table_settings_changed",
  "wall_create",
  "wall_update",
  "wall_remove",
  "wall_batch_create",
  "wall_data",
  "door_toggle",
  "paint_stroke_create",
  "paint_stroke_delete",
  "paint_stroke_clear",
  "paint_sync",
  "paint_template_upsert",
  "paint_template_delete",
  "paint_template_sync",
  "measurement_upsert",
  "measurement_delete",
  "measurement_clear",
  "measurement_sync",
  "layer_settings_update",
  "chat",
  "chat_confirmation",
  "chat_request",
  "chat_moderate",
  "chat_moderation",
  "custom",
] as const;
// END GENERATED MESSAGE TYPES

export interface Message {
  type: MessageType;
  data?: Record<string, unknown>;
  client_id?: string;
  timestamp?: number;
  version: string;
  priority: number;
  sequence_id?: number;
  message_id?: string;
  correlation_id?: string;
  causation_id?: string;
}

interface WireMessage {
  type: MessageType;
  data?: Record<string, unknown>;
  client_id?: string | null;
  timestamp?: number | null;
  version?: string;
  priority?: number;
  sequence_id?: number | null;
  message_id?: string | null;
  correlation_id?: string | null;
  causation_id?: string | null;
}

const messageValidator = new Ajv2020({ allErrors: true });
messageValidator.addKeyword('x-enum-varnames');
const validateWireMessage = messageValidator.compile<WireMessage>(messageSchema);

export type MessageHandler = (message: Message) => Promise<void> | void;

function createMessageId(): string {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
}

/**
 * Create a standardized message with proper formatting
 */
export function createMessage(
  type: MessageType,
  data?: Record<string, unknown>,
  priority: number = 5
): Message {
  return {
    type,
    data: data || {},
    timestamp: Date.now() / 1000,
    version: "0.1",
    priority,
    message_id: createMessageId(),
  };
}

/**
 * Parse incoming JSON message to Message interface
 */
export function parseMessage(jsonStr: string): Message {
  const data: unknown = JSON.parse(jsonStr);
  if (!validateWireMessage(data)) {
    const details = messageValidator.errorsText(validateWireMessage.errors, {
      separator: '; ',
    });
    throw new Error(`Invalid message: ${details}`);
  }

  return {
    type: data.type,
    data: data.data ?? {},
    client_id: data.client_id ?? undefined,
    timestamp: data.timestamp ?? undefined,
    version: data.version ?? "0.1",
    priority: data.priority ?? 5,
    sequence_id: data.sequence_id ?? undefined,
    message_id: data.message_id ?? createMessageId(),
    correlation_id: data.correlation_id ?? undefined,
    causation_id: data.causation_id ?? undefined,
  };
}
