import { vi } from 'vitest';

// Creates a mock RenderEngine with all required methods as vi.fn()
export function createMockRenderEngine() {
  return {
    free: vi.fn(),
    render: vi.fn(),
    resize_canvas: vi.fn(),
    resize: vi.fn(),
    compute_visibility_polygon: vi.fn().mockReturnValue([]),
    add_fog_polygon: vi.fn(),
    remove_fog_polygon: vi.fn(),
    set_ambient_light: vi.fn(),
    set_dynamic_lighting_enabled: vi.fn(),
    handle_wheel: vi.fn(),
    set_zoom: vi.fn(),
    center_camera: vi.fn(),
    set_camera: vi.fn(),
    set_camera_position: vi.fn(),
    set_camera_scale: vi.fn(),
    reset_camera: vi.fn(),
    screen_to_world: vi.fn().mockReturnValue(new Float64Array([0, 0])),
    world_to_screen: vi.fn().mockReturnValue(new Float64Array([0, 0])),
    get_viewport_bounds: vi.fn().mockReturnValue(new Float64Array([0, 0, 800, 600])),
    get_active_table_world_bounds: vi.fn().mockReturnValue(new Float64Array([0, 0, 800, 600])),
    get_cursor_type: vi.fn().mockReturnValue('default'),
    handle_mouse_down: vi.fn(),
    handle_mouse_down_with_ctrl: vi.fn(),
    handle_mouse_move: vi.fn(),
    handle_mouse_up: vi.fn(),
    handle_right_click: vi.fn().mockReturnValue(undefined),
    add_sprite_to_layer: vi.fn().mockReturnValue('sprite_mock_id'),
    remove_sprite: vi.fn().mockReturnValue(true),
    delete_sprite: vi.fn().mockReturnValue(true),
    rotate_sprite: vi.fn().mockReturnValue(true),
    resize_sprite: vi.fn().mockReturnValue(true),
    copy_sprite: vi.fn().mockReturnValue('sprite_copy_id'),
    paste_sprite: vi.fn().mockReturnValue('sprite_paste_id'),
    toggle_grid: vi.fn(),
    set_grid_enabled: vi.fn(),
    toggle_grid_snapping: vi.fn(),
    set_grid_snapping: vi.fn(),
    set_snap_to_grid: vi.fn(),
    set_grid_size: vi.fn(),
    get_grid_size: vi.fn().mockReturnValue(50),
    is_grid_snapping_enabled: vi.fn().mockReturnValue(false),
    set_grid_color: vi.fn(),
    set_background_color: vi.fn(),
    load_texture: vi.fn(),
    add_light: vi.fn(),
    remove_light: vi.fn(),
    set_light_color: vi.fn(),
    set_light_intensity: vi.fn(),
    set_light_radius: vi.fn(),
    toggle_light: vi.fn(),
    update_light_position: vi.fn(),
    get_performance_metrics: vi.fn().mockReturnValue({ fps: 60, sprite_count: 0, render_time_ms: 16 }),
  };
}
