// Comprehensive mock WASM module for unit tests.
// Matches the shape of the real WASM module produced by wasm-bindgen.
// Usage: vi.mock('@lib/wasm', () => ({ wasmManager: mockWasmManager }))

import { vi } from 'vitest';

// ── Mock RenderEngine ─────────────────────────────────────────────────────

export function createMockRenderEngine() {
  return {
    free: vi.fn(),
    render: vi.fn(),
    resize_canvas: vi.fn(),
    resize: vi.fn(),

    // Camera
    handle_wheel: vi.fn(),
    set_zoom: vi.fn(),
    center_camera: vi.fn(),
    set_camera: vi.fn(),
    set_camera_position: vi.fn(),
    set_camera_scale: vi.fn(),
    reset_camera: vi.fn(),
    screen_to_world: vi.fn().mockReturnValue(new Float64Array([0, 0])),
    world_to_screen: vi.fn().mockReturnValue(new Float64Array([0, 0])),
    get_viewport_bounds: vi.fn().mockReturnValue(new Float64Array([0, 0, 800, 600])),
    get_active_table_world_bounds: vi.fn().mockReturnValue(new Float64Array([0, 0, 1000, 1000])),

    // Mouse input
    get_cursor_type: vi.fn().mockReturnValue('default'),
    handle_mouse_down: vi.fn(),
    handle_mouse_down_with_ctrl: vi.fn(),
    handle_mouse_down_with_modifiers: vi.fn().mockReturnValue(undefined),
    handle_mouse_move: vi.fn(),
    handle_mouse_up: vi.fn(),
    handle_right_click: vi.fn().mockReturnValue(undefined),

    // Sprites
    add_sprite_to_layer: vi.fn().mockReturnValue('sprite-1'),
    remove_sprite: vi.fn().mockReturnValue(true),
    delete_sprite: vi.fn().mockReturnValue(true),
    rotate_sprite: vi.fn().mockReturnValue(true),
    resize_sprite: vi.fn().mockReturnValue(true),
    copy_sprite: vi.fn().mockReturnValue(undefined),
    paste_sprite: vi.fn().mockReturnValue('sprite-pasted'),
    get_sprite_info: vi.fn().mockReturnValue(null),
    get_sprite_data: vi.fn().mockReturnValue(null),
    get_sprite_position: vi.fn().mockReturnValue(undefined),
    get_sprite_scale: vi.fn().mockReturnValue(undefined),
    get_sprite_network_data: vi.fn().mockReturnValue(null),
    apply_network_sprite_update: vi.fn(),
    apply_network_sprite_create: vi.fn().mockReturnValue('sprite-net'),
    apply_network_sprite_remove: vi.fn().mockReturnValue(true),
    get_all_sprites_network_data: vi.fn().mockReturnValue([]),

    // Selection
    get_selected_sprites: vi.fn().mockReturnValue([]),
    select_all_sprites: vi.fn(),
    clear_selection: vi.fn(),
    select_sprites_in_rect: vi.fn(),

    // Grid
    toggle_grid: vi.fn(),
    set_grid_enabled: vi.fn(),
    toggle_grid_snapping: vi.fn(),
    set_grid_snapping: vi.fn(),
    set_snap_to_grid: vi.fn(),
    set_grid_size: vi.fn(),
    get_grid_size: vi.fn().mockReturnValue(50),
    is_grid_snapping_enabled: vi.fn().mockReturnValue(false),
    set_grid_color: vi.fn(),

    // Appearance
    set_background_color: vi.fn(),
    load_texture: vi.fn(),

    // Shapes
    create_rectangle_sprite: vi.fn().mockReturnValue('rect-1'),
    create_rectangle_sprite_with_options: vi.fn().mockReturnValue('rect-1'),
    create_circle_sprite: vi.fn().mockReturnValue('circle-1'),
    create_circle_sprite_with_options: vi.fn().mockReturnValue('circle-1'),
    create_line_sprite: vi.fn().mockReturnValue('line-1'),
    create_line_sprite_with_options: vi.fn().mockReturnValue('line-1'),
    create_polygon_sprite: vi.fn().mockReturnValue('poly-1'),
    create_rectangle_sprite_at: vi.fn().mockReturnValue('rect-1'),

    // Lighting
    add_light: vi.fn(),
    remove_light: vi.fn(),
    set_light_color: vi.fn(),
    set_light_intensity: vi.fn(),
    set_light_radius: vi.fn(),
    toggle_light: vi.fn(),
    update_light_position: vi.fn(),
    turn_on_all_lights: vi.fn(),
    turn_off_all_lights: vi.fn(),
    get_light_count: vi.fn().mockReturnValue(0),
    clear_lights: vi.fn(),
    set_ambient_light: vi.fn(),
    set_dynamic_lighting_enabled: vi.fn(),
    get_light_at_position: vi.fn().mockReturnValue(undefined),
    get_light_radius: vi.fn().mockReturnValue(100),
    start_light_drag: vi.fn().mockReturnValue(false),
    update_light_drag: vi.fn().mockReturnValue(false),
    end_light_drag: vi.fn().mockReturnValue(undefined),

    // Fog of war
    add_fog_polygon: vi.fn(),
    remove_fog_polygon: vi.fn(),
    add_fog_rectangle: vi.fn(),
    remove_fog_rectangle: vi.fn(),
    clear_fog: vi.fn(),
    hide_entire_table: vi.fn(),
    is_point_in_fog: vi.fn().mockReturnValue(false),
    get_fog_count: vi.fn().mockReturnValue(0),
    get_fog_at_position: vi.fn().mockReturnValue(undefined),
    start_fog_draw: vi.fn().mockReturnValue('fog-rect-1'),
    update_fog_draw: vi.fn().mockReturnValue(true),
    finish_fog_draw: vi.fn().mockReturnValue(true),
    cancel_fog_draw: vi.fn(),
    set_fog_draw_mode: vi.fn(),
    set_fog_erase_mode: vi.fn(),
    is_in_fog_draw_mode: vi.fn().mockReturnValue(false),

    // Visibility
    compute_visibility_polygon: vi.fn().mockReturnValue([]),

    // GM / user
    set_gm_mode: vi.fn(),
    set_current_user_id: vi.fn(),

    // Input modes
    set_light_drag_mode: vi.fn(),
    is_in_light_drag_mode: vi.fn().mockReturnValue(false),
    get_current_input_mode: vi.fn().mockReturnValue('select'),
    set_input_mode_measurement: vi.fn(),
    set_input_mode_create_rectangle: vi.fn(),
    set_input_mode_create_circle: vi.fn(),
    set_input_mode_create_line: vi.fn(),
    set_input_mode_create_text: vi.fn(),
    set_input_mode_select: vi.fn(),
    set_input_mode_paint: vi.fn(),
    set_input_mode_draw_wall: vi.fn(),
    set_input_mode_create_polygon: vi.fn(),
    cancel_polygon_creation: vi.fn(),
    undo_polygon_vertex: vi.fn(),

    // Layers
    set_layer_opacity: vi.fn().mockReturnValue(true),
    set_layer_visibility: vi.fn().mockReturnValue(true),
    set_layer_blend_mode: vi.fn().mockReturnValue(true),
    set_layer_color: vi.fn().mockReturnValue(true),
    get_layer_settings: vi.fn().mockReturnValue(null),
    get_layer_names: vi.fn().mockReturnValue([]),
    get_layer_sprite_count: vi.fn().mockReturnValue(0),
    set_layer_z_order: vi.fn().mockReturnValue(true),
    clear_layer: vi.fn().mockReturnValue(true),
    clear_all_sprites: vi.fn(),
    set_layer_visible: vi.fn().mockReturnValue(true),

    // Paint system
    paint_set_current_table: vi.fn(),
    paint_get_current_table: vi.fn().mockReturnValue(undefined),
    paint_clear_table: vi.fn(),
    paint_enter_mode: vi.fn(),
    paint_exit_mode: vi.fn(),
    paint_is_mode: vi.fn().mockReturnValue(false),
    paint_set_brush_color: vi.fn(),
    paint_set_brush_width: vi.fn(),
    paint_set_blend_mode: vi.fn(),
    paint_get_brush_color: vi.fn().mockReturnValue(new Float32Array([1, 1, 1, 1])),
    paint_get_brush_width: vi.fn().mockReturnValue(5),
    paint_start_stroke: vi.fn().mockReturnValue(true),
    paint_add_point: vi.fn().mockReturnValue(true),
    paint_end_stroke: vi.fn().mockReturnValue(true),
    paint_cancel_stroke: vi.fn(),
    paint_clear_all: vi.fn(),
    paint_save_strokes_as_sprites: vi.fn().mockReturnValue([]),
    paint_undo_stroke: vi.fn().mockReturnValue(false),
    paint_get_stroke_count: vi.fn().mockReturnValue(0),
    paint_is_drawing: vi.fn().mockReturnValue(false),
    paint_get_strokes: vi.fn().mockReturnValue([]),
    paint_get_current_stroke: vi.fn().mockReturnValue(null),
    paint_on_event: vi.fn(),

    // Actions
    create_table_action: vi.fn().mockReturnValue(null),
    delete_table_action: vi.fn().mockReturnValue(null),
    update_table_action: vi.fn().mockReturnValue(null),
    create_sprite_action: vi.fn().mockReturnValue(null),
    delete_sprite_action: vi.fn().mockReturnValue(null),
    update_sprite_action: vi.fn().mockReturnValue(null),
    set_layer_visibility_action: vi.fn().mockReturnValue(null),
    move_sprite_to_layer_action: vi.fn().mockReturnValue(null),
    batch_actions: vi.fn().mockReturnValue(null),
    undo_action: vi.fn().mockReturnValue(null),
    redo_action: vi.fn().mockReturnValue(null),
    can_undo: vi.fn().mockReturnValue(false),
    can_redo: vi.fn().mockReturnValue(false),
    get_action_history: vi.fn().mockReturnValue([]),
    set_action_handler: vi.fn(),
    set_state_change_handler: vi.fn(),
    set_actions_error_handler: vi.fn(),
    set_actions_auto_sync: vi.fn(),

    // Table data
    get_table_info: vi.fn().mockReturnValue(null),
    get_all_tables: vi.fn().mockReturnValue([]),
    get_sprites_by_layer: vi.fn().mockReturnValue([]),
    get_table_data: vi.fn().mockReturnValue(null),
    get_table_id: vi.fn().mockReturnValue(undefined),
    set_network_client: vi.fn(),
    handle_table_data: vi.fn(),
    handle_sprite_update: vi.fn(),
    send_sprite_move: vi.fn(),
    send_sprite_scale: vi.fn(),
    send_sprite_create: vi.fn(),
    send_sprite_delete: vi.fn(),
    request_table: vi.fn(),
    set_table_received_handler: vi.fn(),
    set_sprite_update_handler: vi.fn(),
    set_table_error_handler: vi.fn(),
  };
}

// ── Mock WASM module ──────────────────────────────────────────────────────

export function createMockWasmModule() {
  return {
    RenderEngine: vi.fn().mockImplementation(() => createMockRenderEngine()),
    PaintSystem: vi.fn().mockImplementation(() => ({
      free: vi.fn(),
      set_current_table: vi.fn(),
      get_current_table: vi.fn().mockReturnValue(undefined),
      clear_table_paint: vi.fn(),
      enter_paint_mode: vi.fn(),
      exit_paint_mode: vi.fn(),
      is_paint_mode: vi.fn().mockReturnValue(false),
      set_brush_color: vi.fn(),
      set_brush_width: vi.fn(),
      set_blend_mode: vi.fn(),
      get_brush_color: vi.fn().mockReturnValue(new Float32Array([1, 1, 1, 1])),
      get_brush_width: vi.fn().mockReturnValue(5),
      start_stroke: vi.fn().mockReturnValue(true),
      add_stroke_point: vi.fn().mockReturnValue(true),
      end_stroke: vi.fn().mockReturnValue(true),
      cancel_stroke: vi.fn(),
      clear_all_strokes: vi.fn(),
      undo_last_stroke: vi.fn().mockReturnValue(false),
      redo_last_stroke: vi.fn().mockReturnValue(false),
      can_undo: vi.fn().mockReturnValue(false),
      can_redo: vi.fn().mockReturnValue(false),
      clear_redo_stack: vi.fn(),
      get_stroke_count: vi.fn().mockReturnValue(0),
      is_drawing: vi.fn().mockReturnValue(false),
      get_all_strokes_json: vi.fn().mockReturnValue([]),
      get_current_stroke_json: vi.fn().mockReturnValue(null),
      get_all_strokes_data: vi.fn().mockReturnValue([]),
      get_strokes_data_json: vi.fn().mockReturnValue([]),
      on_stroke_event: vi.fn(),
      remove_stroke_event: vi.fn(),
    })),
    AssetManager: vi.fn().mockImplementation(() => ({
      free: vi.fn(),
      initialize: vi.fn().mockResolvedValue(undefined),
      download_asset: vi.fn().mockResolvedValue('asset-id'),
      get_asset_data: vi.fn().mockReturnValue(undefined),
      get_asset_info: vi.fn().mockReturnValue(undefined),
      has_asset: vi.fn().mockReturnValue(false),
      has_asset_by_hash: vi.fn().mockReturnValue(false),
      get_asset_by_hash: vi.fn().mockReturnValue(undefined),
      remove_asset: vi.fn().mockReturnValue(false),
      cleanup_cache: vi.fn().mockResolvedValue(undefined),
      get_cache_stats: vi.fn().mockReturnValue('{}'),
      list_assets: vi.fn().mockReturnValue('[]'),
      set_max_cache_size: vi.fn(),
      set_max_age: vi.fn(),
      clear_cache: vi.fn().mockResolvedValue(undefined),
      calculate_asset_hash: vi.fn().mockReturnValue('abc123'),
      get_download_queue_size: vi.fn().mockReturnValue(0),
      get_queued_downloads: vi.fn().mockReturnValue([]),
      clear_download_queue: vi.fn(),
      remove_from_queue: vi.fn().mockReturnValue(false),
    })),
    create_default_brush_presets: vi.fn().mockReturnValue([]),
    version: vi.fn().mockReturnValue('0.1.0'),
    default: vi.fn().mockResolvedValue(undefined),
  };
}
